### ISSUE TITLE
Gradle project sync failed

### ISSUE THREAD

**Issue by ghost** [udacity/ud839_Miwok#10]
When try to import project to studio get error - Gradle project sync failed-Debugging will not work properly

**Comment by benja90** [comment]
@ilkinler do you have Android SDK Build-Tools 23.0.2 (build-tools;23.0.2) ??????

**Comment by Akhil0609** [comment]
i have built tool 25.0.1

**Comment by Akhil0609** [comment]
@benja90 I have built tool 25.0.1

**Comment by KhushbooBaheti** [comment]
@Akhil0609  you have to install built tool 23.0.2

**Comment by Akhil0609** [comment]
@KhushbooBaheti I have installed still it's not working... Plz help me... Share the link correct repository...

**Comment by benja90** [comment]
@Akhil0609 try to up your app/build.grade file with 

apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.1"
    defaultConfig {
        applicationId "com.example.android.justjava"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.0.1'
    testCompile 'junit:junit:4.12'
}

**Comment by Akhil0609** [comment]
@benja90 Bro I dint get this... what to do with this...?? I new to all this Please help me

**Comment by benja90** [comment]
@Akhil0609  Ok, 
I did run the app and changed my Build-Tools to 23.0.2, after I update to 25.0.1 and run fine...
I saw that build.grandle fine did change....  
try first update your file and run.... 
...
the file (build.gradle) is in app folder of your project.


_____________________
sorry for my English.... I speak spanish.......

**Comment by Akhil0609** [comment]
@benja90 @KhushbooBaheti ERROR AT THE MESSAGES
Error:Failed to open zip file.
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a>
<a href="syncProject">Re-download dependencies and sync project (requires network)</a>

**Comment by benja90** [comment]
@Akhil0609  you can see this http://stackoverflow.com/questions/35101206/android-studio-re-download-dependencies-and-sync-project

**Comment by benja90** [comment]
I think that you should update your build proyect settings...

**Comment by rishabhbanga** [comment]
I encountered the same issue, when I had updated the compileSdkVersion, buildToolsVersion, and dependencies to 24. Once I had reverted to the default values provided in the source code, the build still failed citing File path too long on windows, keep below 240 characters error.

Finally when I unzipped the code into a folder on the desktop (earlier the location was 3 more folders inside the same) and entered the configurations given below, it worked:

```
android {
    compileSdkVersion 24
    buildToolsVersion "24.0.3"

    defaultConfig {
        applicationId "com.example.android.miwok"
        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.1.0'
    compile 'com.android.support:support-v4:24.1.0'
    compile 'com.android.support:design:24.1.0'
}

```

**Comment by diwesh87** [comment]
@Akhil0609: Did you get it working?

@rishabhbanga: You are right, the error you get is because Windows handle a deep tree structure extremely poorly unlike Linux. So even if you have just placed the main folder right on your desktop that should have done the trick.

**Comment by Akhil0609** [comment]
@rishabhbanga Bro same error even after changing the app/build.gradle... 
i am using ubuntu... i guess that not a big deal...

**Comment by shalini95** [comment]
I encountered the same error. This fixed it.

https://stackoverflow.com/questions/38442901/gradles-dependency-cache-may-be-corrupt-this-sometimes-occurs-after-a-network

**Comment by Kvaibhav01** [comment]
@ilkinler check that Android Studio refers to a correct version of JDK. Go to **File > Other Settings > Default Project Structure > JDK location and check the path of your JDK.**

**Comment by vcctu85** [comment]
Closing this issue because student's question was answered.
