### ISSUE TITLE
cant resolve method 

### ISSUE THREAD

**Issue by hictors** [udacity/ud839_Miwok#100]
releaseMediaPlayer();
cant resolve method what should I do ??
  private MediaPlayer.OnCompletionListener mCompletionListener = new MediaPlayer.OnCompletionListener() {
        @Override
        public void onCompletion(MediaPlayer mediaPlayer) {
            // Now that the sound file has finished playing, release the media player resources.
          releaseMediaPlayer();
        }
    };

**Comment by Kvaibhav01** [comment]
That certainly means that `releaseMediaPlayer()` was just called and you haven't written the method body. <kbd>Alt+Enter</kbd> should give you more details.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
