### ISSUE TITLE
can't resolve this method 

### ISSUE THREAD

**Issue by Mohamed7422** [udacity/ud839_Miwok#101]
![how to resolve that](https://user-images.githubusercontent.com/41089518/42541203-c559a6ac-84a1-11e8-82c0-0d2d5682840c.png)

**Comment by Kvaibhav01** [comment]
It's most likely that Android Studio is not able to get the `id` of `rootView` from your XML file.

- Make sure you've added the `android:id="@+id/rootView" ` in your XML.
- Double check for typos.
- Try to clean/rebuild the project.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
