### ISSUE TITLE
Error:failed to find target with hash string 'android-23' Install missing platform(s) and sync project.</a>

### ISSUE THREAD

**Issue by Syed-Shahrukh-Hussain** [udacity/ud839_Miwok#102]
Please help me out i find this error when i importing the project

**Comment by Kvaibhav01** [comment]
Here are some solutions:

- Open SDK Manager, check the box on "show package descriptions", select "Google APIs" for the version you are willing to install. Install it and it should solve this. _OR_

- Go to _File -> Invalidate Caches/Restart_   OR

- Remove the _.gradle_ folder in your project folder (if exists). Restart.
