### ISSUE TITLE
Error after importing Miwok into Android Studio

### ISSUE THREAD

**Issue by VBoB13** [udacity/ud839_Miwok#109]
Hi all! I just tried to import Miwok into Android Studios and got the following error:

The versions of the Android Gradle plugin and Gradle are not compatible.
Please do one of the following:<ul><li>Update your plugin to version 2.4. This will require changes to build.gradle due to API changes.
Open migration guide</li><li>Downgrade Gradle to version 3.5.
Fix Gradle wrapper and re-import project</li></ul>

I've done the re-import part and done some other re-sync + restart options but all failed... Anyone have a clue what's going on and how I can solve this?

Thanks in advance!

Keep coding :)

**Comment by TafaraMakaza** [comment]
Hello there: Just make sure you are using the latest version of the gradle distribution and the gradle plugin for android:

1. Go to your build.gradle
2. And put 
 `dependencies {
    classpath 'com.android.tools.build:gradle:3.1.0'
  }`

Hope it helps!

**Comment by VBoB13** [comment]
I did that, but now I get this instead:
Could not find com.android.tools.build:gradle:3.1.0.
Searched in the following locations:
    https://jcenter.bintray.com/com/android/tools/build/gradle/3.1.0/gradle-3.1.0.pom
    https://jcenter.bintray.com/com/android/tools/build/gradle/3.1.0/gradle-3.1.0.jar
Required by:
    project :
Add Google Maven repository and sync project <-- These two are links
Open File <-- These two are links

EDIT:
I clicked on the first link:
- Add Google Maven repository and sync project
and it downloaded the necessary files and I was good to go!

Thanks a lot for the help, @TafaraMakaza ! All help is appreciated now when I am trying to get back into coding 👍
