### ISSUE TITLE
position varable

### ISSUE THREAD

**Issue by Akhil0609** [udacity/ud839_Miwok#11]
I have problem with this line position variable

 Word word = words.get(position);

error: cannot find symbol variable position

**Comment by diwesh87** [comment]
@Akhil0609: public void onItemClick(AdapterView<?> parent, View view, int position, long id)

This is where the position variable is defined. Are you sure you have it the same way, check for variable name in function and for spelling errors too

**Comment by vcctu85** [comment]
Hi @Akhil0609 were you able to resolve your error?

**Comment by vcctu85** [comment]
Closing this issue because student hasn't responded in a week.
