### ISSUE TITLE
getting build faild and   https://jcenter.bintray.com/com/android/tools/lint/lint-gradle/26.1.4/lint-gradle-26.1.4.jar

### ISSUE THREAD

**Issue by sshuklaji962** [udacity/ud839_Miwok#111]
please help

**Comment by Kvaibhav01** [comment]
Can you post a screenshot?

Also check that there is the `google()` repository in your project level build.gradle.

**Comment by sshuklaji962** [comment]
when I downloaded and unzipped the project , then I was getting error that build.gradle missing ....then I import the project through vcs and clone project ....and my project starts with compile to implementation warning.....i changed that too ....but now i have problem with cann't resolve AppCompatActivity ..please solve as soon as project...

**Comment by sshuklaji962** [comment]
![screenshot 189](https://user-images.githubusercontent.com/25439056/46029213-6dc40300-c110-11e8-8b23-34e8e7914e08.png)
![screenshot 190](https://user-images.githubusercontent.com/25439056/46029215-6dc40300-c110-11e8-8c16-d290f4cfde9e.png)
![screenshot 191](https://user-images.githubusercontent.com/25439056/46029216-6e5c9980-c110-11e8-9bb7-013b7e179e97.png)

**Comment by sshuklaji962** [comment]
![screenshot 6](https://user-images.githubusercontent.com/25439056/46029279-92b87600-c110-11e8-8465-5baaed5b07e2.png)
![screenshot 7](https://user-images.githubusercontent.com/25439056/46029280-93510c80-c110-11e8-85e6-ab06ae4dd9a7.png)
![screenshot 8](https://user-images.githubusercontent.com/25439056/46029282-93e9a300-c110-11e8-8821-669f11526c8f.png)

**Comment by Kvaibhav01** [comment]
Try these:

1. Clean and rebuild your project _OR_
2. Do **File -> Invalidate Caches/Restart** _ELSE_

Checkout [this](https://stackoverflow.com/questions/34947794/cant-resolve-appcompatactivity/39980211) Stackoverflow question.

**Comment by SudKul** [comment]
That's right. Sometimes, you need to Invalidate & Restart the IDE. 
Tip: In case you face some unexpected errors with the Emulator, it will be beneficial to wipe out the AVD data by going to Tools >> Device Manager >> Select Device >> Wipe out option.
