### ISSUE TITLE
No toolchains found in the NDK toolchains folder for ABI with prefix: mipsel-linux-android

### ISSUE THREAD

**Issue by ayusmash** [udacity/ud839_Miwok#117]
help please

**Comment by ayusmash** [comment]
No toolchains found in the NDK toolchains folder for ABI with prefix: mipsel-linux-android

**Comment by ayusmash** [comment]
No toolchains found in the NDK toolchains folder for ABI with prefix: mipsel-linux-android

**Comment by Kvaibhav01** [comment]
Upgrade Android Gradle plugin to 3.1 or newer. Add the following in the project level Gradle file:

 `classpath "com.android.tools.build:gradle:3.2.0"`

**Comment by Scott-Raynes** [comment]
Help! I have the same problem. Even i tried to Folk and when i copy the link it shows: 
	Сannot Run Git
	File not found: git.exe
