### ISSUE TITLE
setAdapater crashes in fragment class

### ISSUE THREAD

**Issue by eli94** [udacity/ud839_Miwok#118]
My Miwok app was working fine until I started to use fragments.
I did all the steps, and now when I open numbers activity It crashes. I know that It crashes when it gets to setAdapter line in numberFragment class. (I just applied fragment for numbers for Now)
listView.setAdapter(itemsAdapter);
I searched a lot in StackOverflow and other websites, couldn't get to anywhere.
anybody else got the same problem??

**Comment by UnaLuz** [comment]
Hello, I don't know if you were able to solve this problem, I'm having that same issue right now and I don't know what to do

**EDIT:
I was able to solve the problem, I just forgot to change the ArrayAdapter for the WordAdapter in the numbersActivity.java file *facepalm*
