### ISSUE TITLE
Could not find aapt2-proto.jar (com.android.tools.build:aapt2-proto:0.3.1).

### ISSUE THREAD

**Issue by TheDeepShark** [udacity/ud839_Miwok#119]
Could not find aapt2-proto.jar (com.android.tools.build:aapt2-proto:0.3.1).
Searched in the following locations:
    https://jcenter.bintray.com/com/android/tools/build/aapt2-proto/0.3.1/aapt2-proto-0.3.1.jar

**Comment by Kvaibhav01** [comment]
Try these:
- Upgrade Gradle wrapper (in _gradle-wrapper.properties_ file)
- In your project level _build.gradle_ make sure you have `google()` method to the top of its execution block like this:

```
repositories {
  google() // this
  mavenCentral()
}
```
And then sync/clean/rebbuild project.

**Comment by TheDeepShark** [comment]
Thank's Kvaibhav01,

this is my Gradle-wrapper.properties file (i don't know how I can upgrade it)

`#Wed Oct 24 12:13:13 CEST 2018
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip`

I added the line ( google() ) like this :
`buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        **google()** this line
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

so the app works correctly but I have always some warning message :

> Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

do you have an idea about this message? Thank you

**Comment by Kvaibhav01** [comment]
Yes, if you need to remove those warning just replace `compile` with `implementation`, `testCompile` with `testImplementation` and so on. These are now deprecated and by the end of this year will be extinct from the Android developer world, so it's a good practice to replace them from now. You can find more in detail by visiting the links they've given with the warning information. 

Here is a more detailed answer: https://stackoverflow.com/a/44493379

**Comment by TheDeepShark** [comment]
Thank's

**Comment by Kvaibhav01** [comment]
Let me know if it works and if it does, then close the issue. 😄

**Comment by TheDeepShark** [comment]
Hiii, yes it works ;) big thanks

**Comment by apm-dev** [comment]
I had this problem with :path_provider & aapt2-proto and fix it in this way:

in ***project-folder/gradle/wrapper/gradle-wrapper.properties***

change this:

    distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.2-all.zip
to this:

    distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip

and then in ***project-folder/buil.gradle***

change this:

    classpath 'com.android.tools.build:gradle:3.5.0'

to this:

    classpath 'com.android.tools.build:gradle:4.1.1'
and then run this command

    flutter clean
build or run your project, good luck.
