### ISSUE TITLE
Play one audio song

### ISSUE THREAD

**Issue by Rapter1990** [udacity/ud839_Miwok#12]
When I clicked any item of listview to star the song, it couldn't play it. The songs are in the raw directory of res. How can I solve the problem?

Also, the icon of song file shows "?" , What does it mean? 

Maybe, it can cause the volume to 0 

Here is the code below.

 ```
listView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                //Toast.makeText(NumbersActivity.this,"List Item Clicked",Toast.LENGTH_SHORT).show();
                mediaPlayer = MediaPlayer.create(NumbersActivity.this, R.raw.number_one);
                mediaPlayer.start(); // no need to call prepare(); create() does that for you

            }
        });

```

**Comment by diwesh87** [comment]
Are you saying the icon of the song file shows "?" inside your raw folder? Make sure your "raw" folder is placed under the "res" folder directly and not by mistake became a sub-folder of any other folder. If this is not the case, Build -> Clean and then see if things change.

**Comment by Rapter1990** [comment]
![image](https://cloud.githubusercontent.com/assets/19342017/21921237/b07514f0-d977-11e6-9f7f-feecfa5115ef.png)
Here is the hierarchy of project above.

I did build -> Clean Project , but nothing changed.

**Comment by diwesh87** [comment]
Your code and folder seem right. When there was no music file just the toast message, were you able to see the toast message? If yes, that means the code block is being executed to be the first thing when you click a list item. Secondly, are you running this on an emulator or real device?

**Comment by Rapter1990** [comment]
I'd got toast message and I'd seen "List Item Clicked" message  before I defined the  media player object. What I did to it determines whether the method works or not. The method works so there isn't any issue about about. As your second question , I used genymotion as an emulator. I also checked the volume of emulator . Its volume is max. Where can the issue be? I couldn't find it. Thnk.

**Comment by diwesh87** [comment]
Try running one time on a real device. Sometimes it can be a mere memory and performance issue. Just try once to launch on a real device.

**Comment by Rapter1990** [comment]
When I try to lauch the app on a real device , it works. When I want to launch it on emulator using genymotion, it couldn't occur sounds. I haven't still solve it since my last post. If the problem is caused from memory and performance issue , how will I solve it out? Ths.

**Comment by diwesh87** [comment]
Clearly isn't the issue with the code as I thought. Genymotion is great but in some cases consumes more memory than the default emulator, which of course is slower to start. Memory and performance issue when running on an emulator is solely based on how much your computer can accommodate and allocate.

Thanks & Regards
Diwesh Saxena

**Comment by vcctu85** [comment]
Closing this issue because student's question was answered.
