### ISSUE TITLE
Cannot resolve symbol 'R'

### ISSUE THREAD

**Issue by ghost** [udacity/ud839_Miwok#121]
@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Set the content of the activity to use the activity_main.xml layout file
    setContentView(R.layout.activity_main);
}
In this Mainactivity.java in the java file, the R is highlighted red when I put the mouse on it. And it says Cannot resolve symbol 'R'. How can I fix this?

**Comment by Kvaibhav01** [comment]
Here are some solutions:

1. Build -> Clean Project
2. Build -> Rebuild Project
3. Tools -> Android -> Sync Project with Gradle Files
4. File -> Invalidate Caches / Restart... -> Invalidate and Restart

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
