### ISSUE TITLE
change dependencies as per latest version

### ISSUE THREAD

**Issue by Warrioravi** [udacity/ud839_Miwok#124]
build.gradle needs to be updated .
**classpath 'com.android.tools.build:gradle:2.1.0'** _needs to be changed to_
**classpath 'com.android.tools.build:gradle:3.2.1'**

**Comment by Kvaibhav01** [comment]
Hey! I think you did that in #123. If you're done, just close this issue. 😀

**Comment by Warrioravi** [comment]
![](https://assets-cdn.github.com/images/icons/emoji/unicode/1f600.png)
closing this issue
