### ISSUE TITLE
 Failed to capture snapshot of input files for task ':app:mergeDebugResources' property 'aapt2FromMaven' during up-to-date check.

### ISSUE THREAD

**Issue by reeshabhranjan** [udacity/ud839_Miwok#126]
This is the screenshot:
![image](https://user-images.githubusercontent.com/25811225/49538449-75aed900-f8f1-11e8-8ce0-f2685b323755.png)

**Comment by Kvaibhav01** [comment]
Go Settings > Gradle > Android Studio. Then check "Enable embedded Maven repository"

**Comment by reeshabhranjan** [comment]
> Go Settings > Gradle > Android Studio. Then check "Enable embedded Maven repository"

It is working, but getting some warnings.

![image](https://user-images.githubusercontent.com/25811225/49595789-c9c3c700-f99e-11e8-9305-5f7b4ea59421.png)

![image](https://user-images.githubusercontent.com/25811225/49595812-dc3e0080-f99e-11e8-8b50-bf04be65fa5a.png)

**Comment by Kvaibhav01** [comment]
You can replace them. Like replacing `compile` with `implementation`. This will not effect your project but is a recommended way.

**Comment by WERMAR** [comment]
@Kvaibhav01 I activate the embedded Maven repository but get the same error again. Did you have a other idea, for a resulution? Thanks for help

**Comment by Kvaibhav01** [comment]
@WERMAR, I'm afraid that this is the only way I know:

> Go Settings > Gradle > Android Studio. Then check "Enable embedded Maven repository"

@reeshabhkumarranjan's issue was resolved with this.
