### ISSUE TITLE
completed project (?)

### ISSUE THREAD

**Issue by ghost** [udacity/ud839_Miwok#128]
Hi. I've just started this topic and as I downloaded the package, turs out it's in advanced stage. There are all 5 activites created, 5 *.java files, with a lot of code.
Is it ok? :)
![image](https://user-images.githubusercontent.com/44138626/49702404-00484e80-fbf8-11e8-801d-c3c3a2b825d7.png)

**Comment by Kvaibhav01** [comment]
I think you downloaded the wrong branch. Check out the [Starter-Code branch](https://github.com/udacity/ud839_Miwok/tree/Starter-code). Download it, and open it in Android Studio. In this, you'll get just a single activity.
