### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by TrishStandley** [udacity/ud839_Miwok#129]
I cannot run app on my phone because I continue to get this error message:

Error running 'NumbersActivity': The activity must be exported or contain an intent-filter

I am cutting and pasting what I have in Java & Layout

public void openNumbersList(View view) {
        Intent i  = new Intent(this, NumbersActivity.class);
        startActivity(i);

<TextView
        android:id="@+id/numbers"
        style="@style/CategoryStyle"
        android:background="@color/category_numbers"
        android:text="@string/category_numbers"
        android:onClick="openNumbersList"/>

NOTE: I also have an error on my inActivity.java that states:

File was loaded in the wrong encoding: 'UTF-8'

**Comment by Kvaibhav01** [comment]
Hi @TrishStandley! Make sure your _AndroidManifest.xml_ file has the following code inside the `NumbersActivity`'s `<activity>` tag:

```
<intent-filter>
	<category android:name="android.intent.category.LAUNCHER" />
</intent-filter>
```
Else, just choose _Select Run/Debug Configuration_ and change it from from your activity to _App_. Checkout [this screenshot](https://i.stack.imgur.com/cIwGj.png) for reference.

**Comment by TrishStandley** [comment]
The second option worked THANK YOU!!!

BTW do you know how to fix this issue? I still have it and it isn't allowing me to load app on my phone. I get error: unmappable character for encoding UTF-8

NOTE: I also have an error on my inActivity.java that states:

File was loaded in the wrong encoding: 'UTF-8'

**Comment by Kvaibhav01** [comment]
For _error: unmappable character for encoding UTF-8_ you can do this:

File -> Settings -> Editor -> File encodings -> set UTF-8 for IDE Encoding, Project Encoding, Default encoding properties file. Then rebuild the project (Build -> Rebuild project).

As for the _file was loaded in the wrong encoding: 'UTF-8'_, click the 'Reload in another encoding' link. If you want UTF-8, then goto 'more -> UTF-8'.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo.
