### ISSUE TITLE
getting bytecode to dec and null point exception errors

### ISSUE THREAD

**Issue by karan169** [udacity/ud839_Miwok#13]
Error:Error converting bytecode to dex:
Cause: java.lang.RuntimeException: Exception parsing classes
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
Error:1 error; aborting

**Comment by vcctu85** [comment]
@karan169 Try cleaning your project, and running it again. Let me know if that works!

**Comment by karan169** [comment]
yeah worked bruh thank a lot!! @vcctu85

**Comment by vcctu85** [comment]
Closing this issue because student's question was answered.
