### ISSUE TITLE
The repository is not working properly, not able to compile.

### ISSUE THREAD

**Issue by shivam-aggarwal** [udacity/ud839_Miwok#130]
![screenshot 19](https://user-images.githubusercontent.com/37217374/50561585-2a41ec00-0d32-11e9-972e-7d1c61336fba.png)
Please  help with the above.

**Comment by Kvaibhav01** [comment]
This might be your antivirus issue. Try to disable it and check. Else disable Instant Run feature as: 

1. Open the Settings or Preferences dialog: On Windows or Linux, select File > 
Settings from the menu bar. 
2.  Navigate to Build, Execution, Deployment > Instant Run.
3.  Uncheck The box next to Restart activity on code changes.
