### ISSUE TITLE
Could not run build action using Gradle distribution 

### ISSUE THREAD

**Issue by saoodahmad** [udacity/ud839_Miwok#135]
Could not run build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-2.10-all.zip'.
Help me with the error

**Comment by Kvaibhav01** [comment]
Follow these steps:

1. Close Android Studio (AS)
2. Delete the folder in C:\Users\.gradle\wrapper\dists\gradle-2.10-all
3. Run AS as admin
4. Sync your project files 

Make sure you have a good internet connection throughout the process.

**Comment by srigithub26** [comment]
what will be the next screen after login submit?

**Comment by AbhishekPrakash5** [comment]
it is not working for me. i deleted the C:\Users.gradle\wrapper\dists\gradle-2.10-all, but its still showing the same error. I have made a new issue about is just now (https://github.com/udacity/ud839_Miwok/issues/183).

**Comment by benjiboy50fonz** [comment]
If one were to have the same issue, yet no admin rights, would that be the cause?

**Comment by lycoris106** [comment]
How come I cannot find Users.gradle\wrapper\dists\gradle-2.10-all in my computer?

**Comment by SudKul** [comment]
Sometimes, you need to Invalidate & Restart the IDE. 
Tip: In case you face some unexpected errors with the Emulator, it will be beneficial to wipe out the AVD data by going to Tools >> Device Manager >> Select Device >> Wipe out option.
