### ISSUE TITLE
For anyone in 2019 having an issue building after import

### ISSUE THREAD

**Issue by wachiranduati** [udacity/ud839_Miwok#138]
I'm assuming you have the latest android studio version
You might also have issues with an error indicating that the NDK tool has an issue too...
I solved all this by removing the tool 
`settings` -> `system settings` -> `android sdk` - > `sdk tools`
`NDK` should appear in the list just above the `support repository` category

Other errors after this might refer to compile being outdated which will generally require you to update the compile tags in your `Gradle scripts` - > `build.gradle(Module:app)` to implementation and remember to update the buildToolsVersion which might be another one of the errors.
Your final code for `build.gradle(Module:app)` should look like

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "28.0.3"

    defaultConfig {
        applicationId "com.example.android.miwok"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation 'com.android.support:appcompat-v7:23.3.0'
    implementation 'com.android.support:support-v4:23.3.0'
    implementation 'com.android.support:design:23.3.0'
}
`

NEXT ...update the `build.gradle(Module:app)`
you might run into an error requiring you to this file by adding the google() line under jcenter

`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        google()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

I really hope this helps someone out. It took me 15+ hours to scour the internet for that solution.
Cheers!

**Comment by ritvikbhawnani** [comment]
I followed your suggestions. Unfortunately, I am unable to run on my device (Nexus 6P 8.1 API 27). I can run on an emulator Pixel 2 (API 28).

I get the following error when running on my device...

`Error while executing: am start -n "com.example.android.miwok/com.example.android.miwok.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.example.android.miwok/.MainActivity }
Error type 3
Error: Activity class {com.example.android.miwok/com.example.android.miwok.MainActivity} does not exist.

Error while Launching activity`

**Comment by wachiranduati** [comment]
I hope you started out your project by first cloning their repo the [udacity miwok repository](https://github.com/udacity/ud839_Miwok)..for some reason the download link provided in the course wasn't working out for me too..
on a different note...your error seems to state that you're missing the mainActivity class that's super off unless you named your mainActivity differently..kindly try checking and confirm this...else just share your code and I'll try help if I can..

**Comment by TheRealRedJohn** [comment]
For your reference. It looks like it is named correctly. Also, I have tried changing from 23.3.0 to 23.4.0 (highlighted section in build.gradle (app)) but it does seem to fix the issue. 

![Annotation 2019-03-21 034603](https://user-images.githubusercontent.com/25170682/54741374-45cbce80-4b8c-11e9-998d-b9f7b210d35a.png)
![Annotation 2019-03-21 034707](https://user-images.githubusercontent.com/25170682/54741389-4d8b7300-4b8c-11e9-811d-3c840f335679.png)
![Annotation 2019-03-21 034814](https://user-images.githubusercontent.com/25170682/54741394-511efa00-4b8c-11e9-82a4-766b094ed571.png)

Thank you for taking the time

**Comment by ritvikbhawnani** [comment]
**I fixed the issue!**
Thank you for your help @wachiranduati 

Although I do not fully understand why, apparently the Miwok app was installed on a different device, at least that's what it said on my phone settings. I managed to uninstall it and that seemed to work. Sorry for the inconvenience!

**Comment by wachiranduati** [comment]
awesomee....I'm glad you were able to solve it..

**Comment by ghost** [comment]
Hey, I had the above issues and I resolved them by your solution but I get the error "cannot resolve symbol R". It doesn't get resolved even after cleaning the project and syncing with gradle files. Please help.

**Comment by wachiranduati** [comment]
@magnificientSteiner R is more like a resource finder at refers to elements on your view that are referenced via and ID just look through your app again to ensure the view exists...I'd advice you to first located all the R.id.sth's that exist on your javaClasses eg MainActivity Number Activity etc and ensure that the view id being referenced actually exists...Android Studio should actually show an Error if your codebase has on...just look to the top right corner of your IDE and be on the lookout for a red Apostrophe

**Comment by RimmaKS** [comment]
@wachiranduati Thank you!

**Comment by ghost** [comment]
@wachiranduati I've just imported the miwok code from github and made the changes you suggested. No ids have been created but I still get the error "cannot Resolve symbol R".

**Comment by wachiranduati** [comment]
@magnificientSteiner try this [cannot find R](https://stackoverflow.com/questions/17054000/cannot-resolve-symbol-r-in-android-studio)

**Comment by ghost** [comment]
@wachiranduati Thanks, I solved it.

**Comment by artmatir** [comment]
@wachiranduati why i still cannot run the application?can you kindly resolve my problem?
the error says ""Session 'app': Error Installing APKs""

**Comment by wachiranduati** [comment]
@artmatir  please make sure that you do not have another version of the same app installed on your phone then restart it the phone....should you get another error...kindly post the error you get...the one you stated is kinda general.....check your logcat for more detailed messages

**Comment by Nic008888** [comment]
I can't get this to work. 
Error:

Failed to resolve: com.android.support:appcompat-v7:23.3.0 Add Google Maven repository and sync projectShow in Project Structure dialog Affected Modules: app |  
-- | --
Failed to resolve: com.android.support:support-v4:23.3.0 Add Google Maven repository and sync projectShow in Project Structure dialog Affected Modules: app |  
Failed to resolve: com.android.support:design:23.3.0 Add Google Maven repository and sync projectShow in Project Structure dialog Affected Modules: app |

**Comment by wachiranduati** [comment]
@Nic008888 I think you added the maven dependency to the wrong grade file.....note that theres two gradle files in you android project so add the dependency on the proper gradle file...i.e. the project gradle file is where the maven dependency should be added.

**Comment by xMagicXs** [comment]
for me was easier to update my android studio with all SDK and NDK files then i imported the files again and updated everithing it showed and worked like a charm and lastly it asked me if i want to upgrade graddle to my version of android studio ( do that last otherwise will give u the maven error and wont work) also min sdk in app is 15 so you need to download that too soo..might as well download everithing to have ur android studio complete and in the future you wont find any inssues while importing any kid of projects both new and old :P ( instead of bandaging that wound make sure you dont get wounded in the first place :P )

**Comment by wachiranduati** [comment]
And so the thread was closed and everybody lived happily ever after.The end. Thanks @xMagicXs for that...I'd forgotten about this thread.

**Comment by Skullbreakz** [comment]
thanks a lot now my code works.

**Comment by tanyaagrawal1006** [comment]
@wachiranduati I did everything that you've written here to do. But, there is this error that pops in when I try to run it on my device.

ERROR: Could not find method google() for arguments [] on repository container.

Can you please help me?

**Comment by Nic008888** [comment]
I never managed to get that import to work, so in the end I just redesigned it. Took about 10 Min the only thing they had in there was some XML coding as far as I remember

**Comment by ghost** [comment]
Hello what should i do after this:
ERROR: Could not find method implementation() for arguments [directory 'libs'] on project ':app'.
Open File.

and what is this (adding the google() line under jcenter) can be more explanation?

**Comment by wachiranduati** [comment]
> Hello what should i do after this:
> ERROR: Could not find method implementation() for arguments [directory 'libs'] on project ':app'.
> Open File.
> 
> and what is this (adding the google() line under jcenter) can be more explanation?

Kindly try @xMagicXs solution...it seems to be the easiest way out of this.
