### ISSUE TITLE
How can i solve this issue?

### ISSUE THREAD

**Issue by Hegazy1** [udacity/ud839_Miwok#141]
How can i solve this issue ?
![kkkf](https://user-images.githubusercontent.com/38706973/56461116-afb6de00-63ad-11e9-84bc-565f89ec8b68.PNG)

**Comment by redaxxxx** [comment]
open view from above bar>select tools window>gradle>toggle offline mode , and then sync gradle

**Comment by SudKul** [comment]
Should you (or any learner) need help on individual issues, we recommend using the https://knowledge.udacity.com/ platform to discuss with our experienced mentors.
