### ISSUE TITLE
How can i solve this problem ?

### ISSUE THREAD

**Issue by Hegazy1** [udacity/ud839_Miwok#142]
How can i solve this problem ?
![57485962_274408223464936_2364395155898761216_n](https://user-images.githubusercontent.com/38706973/56467802-f1826b80-6423-11e9-9a55-71439d36efa2.png)

**Comment by Kvaibhav01** [comment]
Try this solution: https://stackoverflow.com/a/25329580
Also, the same goes for your another issue #141

**Comment by SudKul** [comment]
Should you (or any learner) need help on individual issues, we recommend using the https://knowledge.udacity.com/ platform to discuss with our experienced mentors.
