### ISSUE TITLE
Add Google maven repository

### ISSUE THREAD

**Issue by Francis-Njoku** [udacity/ud839_Miwok#143]
Hi, I saw this on event log when I tired to build

```
ERROR: Failed to resolve: com.android.support:appcompat-v7:23.3.0
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: app


ERROR: Failed to resolve: com.android.support:support-v4:23.3.0
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: app


ERROR: Failed to resolve: com.android.support:design:23.3.0
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: app
```

**Comment by Kvaibhav01** [comment]
In your project's _build.gradle_ file, add `google()` into the `repositories` blocks like this:

```
repositories {
    jcenter()
    google() // add this
}
```

Next, update the Gradle version like `classpath 'com.android.tools.build:gradle:YOUR_NEW_VERSION'`

Sync and rebuild the project.

**Comment by saqlain17** [comment]
Didn't worked

**Comment by akhilksugathan** [comment]
Add this code to build.gradle, repositories -
maven {
            url 'https://maven.google.com'
        }
        jcenter()
        maven { url 'https://maven.fabric.io/public' }

**Comment by ShabieHassan** [comment]
Just click on the red line that show "Add google maven repository and small windows pops up,  just see here **refract do** and click it.
This solve my problem

**Comment by Hatzlacha** [comment]
> Add this code to build.gradle, repositories -
> maven {
> url 'https://maven.google.com'
> }
> jcenter()
> maven { url 'https://maven.fabric.io/public' }

This worked for me. This has been so frustrating to get working. THanks for your help

**Comment by ghost** [comment]
Hi, I am a newbie, i was able to change the gradle plugin version and gradle version and also added the google repo. I am just confused, that to run such files we need to install the required sdk and update the project's gradle version everytime, right?

**Comment by SudKul** [comment]
No longer needed. We are using the `mavenCentral()` now. 
We have updated all branches to use Gradle 7.x, SDK API level 31, and AndroidX dependencies.
