### ISSUE TITLE
Gradle Sync Issue

### ISSUE THREAD

**Issue by imabhisht** [udacity/ud839_Miwok#144]
How can i solve this issue!!
[ud839_Miwok]
![#@323](https://user-images.githubusercontent.com/51349137/58958718-29215900-87c1-11e9-8a18-3bafea6eef10.PNG)

build.gradle is:-
![2323](https://user-images.githubusercontent.com/51349137/58958797-4eae6280-87c1-11e9-8e8a-0d1d79e23a6f.PNG)
![sdsdsdsaAA](https://user-images.githubusercontent.com/51349137/58958815-5837ca80-87c1-11e9-8801-3755661a8f73.PNG)

Plz help. Im new on these.....

**Comment by RobFromFla** [comment]
I have the same issues. I have tried following some tips on some other posts but to no avail. I've been getting through these courses pretty well, but am at a full stop right here. :-(

**Comment by mohkatta** [comment]
same issue
unable to continue

**Comment by redaxxxx** [comment]
open view from the above  bar>tools window>gradle>toggle ofline mode , then sync gradle

**Comment by SudKul** [comment]
These error will not occur again. Use the latest IDE. 
We have updated all branches to use Gradle 7.x, SDK API level 31, and AndroidX dependencies as of 2022.
