### ISSUE TITLE
Action bar not showing

### ISSUE THREAD

**Issue by venkyvc** [udacity/ud839_Miwok#149]

**Comment by OlgasArt** [comment]
Hi, did you try?

" - Add the v7 appcompat support library to your project, as described in Support Library Setup.
- Make sure the activity extends AppCompatActivity"

Source: https://developer.android.com/training/appbar/setting-up.html

**Comment by venkyvc** [comment]
I added the v7 app compat library and also main activity extended to app compat but still the action bar isn't showing
