### ISSUE TITLE
problem with the nested linear layout 

### ISSUE THREAD

**Issue by md-x1** [udacity/ud839_Miwok#150]
I finish all the steps in lesson 4 (visual polish) put this is the result can't find the problem
![Screenshot_2019-06-24-19-28-11](https://user-images.githubusercontent.com/52172137/60036483-fd0a4100-96b7-11e9-9de7-409a5103f71d.png)

**Comment by LaszloLajosT** [comment]
I am not sure what is the problem... Do you mean you can't scroll down? All you need to do ( in that case) that use a ScrollView in list_item.xml.
