### ISSUE TITLE
Failed to open the project

### ISSUE THREAD

**Issue by Mannytz** [udacity/ud839_Miwok#16]
I keep getting the error " Failed to find build tools revision 23.0.2", but even after installing the same error shows up.
![ud839_miwok-starter-code - cusersmanfreddesktopud839_miwok-starter-code - android studio 2 1 3](https://cloud.githubusercontent.com/assets/25842912/23063211/5d082028-f51a-11e6-9ebb-0689e9807eda.jpg)

**Comment by thomaslian** [comment]
Go to your SDK manager, check which build tools you are using (i'm currently on 25.0.2). Edit your build.gradle file (you will find it under the app folder) to the version you are using.

Example: buildToolsVersion "25.0.2"

**Comment by Mannytz** [comment]
Thanks alot, it worked.
On 19 Feb 2017 10:51, "thomaslian" <notifications@github.com> wrote:
>
> Go to your SDK manager, check which build tools you are using (i'm
currently on 25.0.2). Edit your build.gradle file (you will find it under
the app folder) to the version you are using.

**Comment by Ayush-Goyal-coding** [comment]
Simplest solution go to any previous project,open its build.gradle file and then compare both the build.gradle files and update Yours accordingly
Below is the my code (it worked for me)


````
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"

    defaultConfig {
        applicationId "com.example.android.miwok"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.1.1'
    testCompile 'junit:junit:4.12'
}

```

Hope that helps

**Comment by beratcelik** [comment]
You most probably **open**ed the project rather than **import**ing.
Try File->New->Import Project. You will still get notified to install some updates. Do install them. But this time it will work.

**Comment by vcctu85** [comment]
Closing this issue because student's question was answered.
