### ISSUE TITLE
Ambiguous method call. Both findViewById (int) in AppCompatActivity and findViewById (int) in Activity match 

### ISSUE THREAD

**Issue by dakshina13** [udacity/ud839_Miwok#165]
Please help he resolve this issue. I have tried the solution in the stackoverflow page.
but that has been of no help.The error popped up all of a sudden. And I'm new to android programming.Can someone please help me.

**Comment by SudKul** [comment]
Should you (or any learner) need help on individual issues, we recommend using the https://knowledge.udacity.com/ platform to discuss with our experienced mentors.
