### ISSUE TITLE
Tutorial: How to fix your import issues! (Working in 7.27.2019)

### ISSUE THREAD

**Issue by Blankedmaker** [udacity/ud839_Miwok#168]
Alright, I'm a bit of a dumbass when it comes to this stuff, and I've finally figured out how to get this working after almost giving up and skipping the course. And now I'll help you get it  working too!

0. Literally delete everything related to the Miwok app course that you've downloaded before, any folder or anything related to the repository, get rid of it if whatever you tried didn't work initially, it won't work now. You're going to be starting this from the ground up.

1. Open Android Studio. File > Settings > Search "Android SDK" > in the SDK Platforms tab, download and install all the Android API s from level 15 to 23. And in the SDK Tools tab, check the "Show Package Details" box at the bottom right, then download and install SDK Build-Tool version 27.0.3.

2. Get the https link from either your fork or [Udacity's Miwok's ](https://github.com/udacity/ud839_Miwok) repository from the "Clone or download" tab, and copy it.

3. Open Android Studio. File > New > Import from Version Control > Git > paste your the link from the previous step to the URL (Make sure the folder/directory you're downloading the repository in is named ``ud839_Miwok`` for the sake of consistency). 

4. (IMPORTANT) Wait a bit, and it'll notify you to update your Gradle plugins, it'll probably be a pop-up notification near bottom right, accept it! This step is crucial and important. It'll then give you this following error: 
https://i.imgur.com/JPctl3u.png

```ERROR: Failed to resolve: com.android.support:appcompat-v7:23.3.0
Add Google Maven repository and sync project
Show in Project Structure dialog
Affected Modules: app
```

Click on the "app" highlighted in blue, in your dependencies, change every ``compile`` and ``testCompile`` to ``implementation``  and ``testImplementation`` respectively.

Then click on "Add Google Maven repository and sync project" in the error menu highlighted in blue, then click on "Do Refactor".
https://i.imgur.com/e9eS8Ie.png

5. (Optional step for those who aren't well-versed in Git), go to the VCS option at the top bar and from there VCS > Git > Branches > Starter-code > Checkout As > Ok, and now you're ready to start with the course! If you want to change to any specific branch, then refer back to this step. As a side note, I strongly recommend taking Udacity's [Unix Command Line Basics](https://classroom.udacity.com/courses/ud595/lessons/4597278561/concepts/46968695970923) and [How To Use Git & Github](https://classroom.udacity.com/courses/ud775) courses if you want to become a much more competent programmer with Git and command lines in general.

Note: A few of these steps, probably the ones related with changing  ``compile`` to ``implementation`` 
 in dependencies, *might* be unnecessary, but do them *just* to be on the safe side.

Aaaand, voila! You're ready to rock the world.

**Comment by pratikparamane98** [comment]
Thank you

**Comment by hafizhuzaifabit** [comment]
i'm facing several issues plz help me to sort out

**Comment by ELAJI** [comment]
ohhhhh thank you

**Comment by CamilleAnneJ** [comment]
Hi @Blankedmaker 
I am a beginner in programming and using Android Studio.
I tried to work on Miwok project, so I followed your tutorial. 
Unfortunately, when I have to paste the URL of the project, for the "startercode", it is highlight in red and directly erased (when I have to import the project).
I tried the same approach with "Lesson one" and it works until the last step, after it fails. 
Can you help me on this?  May be I am missing something.
Thank you.

**Comment by ELAJI** [comment]
hello

can you send me a scren of errors

me to im a beginning developer

if i can halp you, with pleasure

Le dim. 17 nov. 2019 à 20:55, CamilleAnneJ <notifications@github.com> a
écrit :

**Comment by CamilleAnneJ** [comment]
Hej,
Thank you.
I will take some screenshots in the following days.
Thank you for helping.
Camille

Camille JOURDAIN

- Research Engineer in Eco-design -

**Comment by ELAJI** [comment]
you welcome

Le ven. 22 nov. 2019 à 13:43, CamilleAnneJ <notifications@github.com> a
écrit :

> Hej,
> Thank you.
> I will take some screenshots in the following days.
> Thank you for helping.
> Camille
>
> Camille JOURDAIN
>
> - Research Engineer in Eco-design -
>
>
>
>

**Comment by EnterGM** [comment]
I got error : ERROR: Could not find method implementation() for arguments [directory 'libs'] on project ':app'.

**Comment by CamilleAnneJ** [comment]
![Annotation 2019-12-01 162727](https://user-images.githubusercontent.com/57873847/69916600-488dfb80-145d-11ea-838d-ad5be8c47c21.png)

**Comment by CamilleAnneJ** [comment]
![Annotation 2019-12-01 162445](https://user-images.githubusercontent.com/57873847/69916606-5774ae00-145d-11ea-829a-ed3c184acb67.png)

**Comment by CamilleAnneJ** [comment]
This is what we get. 
I know that it is not a lot of detail but I am stuck from the beguinning unfortunately.

**Comment by LaszloLajosT** [comment]
Hi Camille,
You can download the project in zip from GitHub and copy the project to wherever you wish on your computer. After that, you can open it from Android Studio.

**Comment by St3ve1988** [comment]
**ERROR: Could not find method implementation() for arguments [directory 'libs'] on project ':app'.**
I have this error after completing all steps through 4 and clicking the "Do Refractor" button.

**Comment by St3ve1988** [comment]
> **ERROR: Could not find method implementation() for arguments [directory 'libs'] on project ':app'.**
> I have this error after completing all steps through 4 and clicking the "Do Refractor" button.

Nevermind, I fixed it. I had forgotten to update gradle.

**Comment by DVOfficial** [comment]
Thank Blankedmaker, 

> Alright, I'm a bit of a dumbass when it comes to this stuff, and I've finally figured out how to get this working after almost giving up and skipping the course. And now I'll help you get it working too!
> 
> 1. Literally delete everything related to the Miwok app course that you've downloaded before, any folder or anything related to the repository, get rid of it if whatever you tried didn't work initially, it won't work now. You're going to be starting this from the ground up.
> 2. Open Android Studio. File > Settings > Search "Android SDK" > in the SDK Platforms tab, download and install all the Android API s from level 15 to 23. And in the SDK Tools tab, check the "Show Package Details" box at the bottom right, then download and install SDK Build-Tool version 27.0.3.
> 3. Get the https link from either your fork or [Udacity's Miwok's ](https://github.com/udacity/ud839_Miwok) repository from the "Clone or download" tab, and copy it.
> 4. Open Android Studio. File > New > Import from Version Control > Git > paste your the link from the previous step to the URL (Make sure the folder/directory you're downloading the repository in is named `ud839_Miwok` for the sake of consistency).
> 5. (IMPORTANT) Wait a bit, and it'll notify you to update your Gradle plugins, it'll probably be a pop-up notification near bottom right, accept it! This step is crucial and important. It'll then give you this following error:
>    https://i.imgur.com/JPctl3u.png
> 
> ```
> Add Google Maven repository and sync project
> Show in Project Structure dialog
> Affected Modules: app
> ```
> 
> Click on the "app" highlighted in blue, in your dependencies, change every `compile` and `testCompile` to `implementation` and `testImplementation` respectively.
> 
> Then click on "Add Google Maven repository and sync project" in the error menu highlighted in blue, then click on "Do Refactor".
> https://i.imgur.com/e9eS8Ie.png
> 
> 1. (Optional step for those who aren't well-versed in Git), go to the VCS option at the top bar and from there VCS > Git > Branches > Starter-code > Checkout As > Ok, and now you're ready to start with the course! If you want to change to any specific branch, then refer back to this step. As a side note, I strongly recommend taking Udacity's [Unix Command Line Basics](https://classroom.udacity.com/courses/ud595/lessons/4597278561/concepts/46968695970923) and [How To Use Git & Github](https://classroom.udacity.com/courses/ud775) courses if you want to become a much more competent programmer with Git and command lines in general.
> 
> Note: A few of these steps, probably the ones related with changing `compile` to `implementation`
> in dependencies, _might_ be unnecessary, but do them _just_ to be on the safe side.
> 
> Aaaand, voila! You're ready to rock the world.

Thanks,with your support,It works

**Comment by vveliu** [comment]
This is awesome. Thank you very much, you saved my day.

**Comment by valensasB** [comment]
thanks @Blankedmaker I was stuck here for few days just to start this app, now I am getting back my wish to learn again

**Comment by ishasahni2000** [comment]
> > **ERROR: Could not find method implementation() for arguments [directory 'libs'] on project ':app'.**
> > I have this error after completing all steps through 4 and clicking the "Do Refractor" button.
> 
> Nevermind, I fixed it. I had forgotten to update gradle.

@St3ve1988 how did you fix it, I am having the same error

**Comment by carloscampo5200** [comment]
Great!

**Comment by Aishwarya2k7** [comment]
Thanks a lot. Much appreciated.

**Comment by GuilleJOA** [comment]
Wow it works! Thank you sir!

**Comment by hi-nikhil** [comment]
Thanks a lot man..
** Do'nt use ( ) after implementation and testImplementation

**Comment by rasool414** [comment]
thank you so much i did on second time

**Comment by sharanaditya007** [comment]
Hello

I am still getting this error attached. Even upgraded the gradle to4.8 version but still the same.. Can somebody help me?
![Capture](https://user-images.githubusercontent.com/59566961/129603486-bc2239e3-186c-47bc-a650-2e93c8dd2548.PNG)

**Comment by SudKul** [comment]
The issue was due to the deprecated gradle build tool version in project level gradle:
```
dependencies {
    classpath 'com.android.tools.build:gradle:X.X.X'
}
```
