### ISSUE TITLE
Nothing displays on my screen

### ISSUE THREAD

**Issue by ib1980** [udacity/ud839_Miwok#17]
I cannot get the code to run on my phone.  I even copied and pasted to android studio and still my phone just shows a blank screen

**Comment by vcctu85** [comment]
Hi @ib1980 , does the code run on your emulator? Let me know!

**Comment by Kvaibhav01** [comment]
@ib1980 try to build or rebuild your project in Android Studio and fix the error(s) if there are any.

**Comment by johnshea** [comment]
Issue creator has not responded.
