### ISSUE TITLE
GRADLE ERROR FIX

### ISSUE THREAD

**Issue by DariusThurman** [udacity/ud839_Miwok#171]
apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion '27.0.3'

    defaultConfig {
        applicationId "com.example.android.miwok"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])	
    testCompile 'junit:junit:4.12'	
    compile 'com.android.support:appcompat-v7:23.3.0'	
    compile 'com.android.support:support-v4:23.3.0'
    compile 'com.android.support:design:23.3.0'
}

**Comment by DariusThurman** [comment]
I have a solution for the gradle error.

**Comment by dev-aminmo** [comment]
Thank you it works

**Comment by yogi-28698** [comment]
It is showing,  Gradle project sync failed. Basic Functionality (e.g editing debugging) will not work properly.
Please Help.......

**Comment by SudKul** [comment]
We have updated all branches to use Gradle 7.x, SDK API level 31, and AndroidX dependencies.
