### ISSUE TITLE
.setOnClickListener (New)

### ISSUE THREAD

**Issue by Bruines** [udacity/ud839_Miwok#173]
for some reason "new" is always in red ex. .setOnClickListener(new onClickListener).
what am i doing wrong? 
![new onClickListener](https://user-images.githubusercontent.com/55665202/65391804-9f949780-dd6d-11e9-997b-b67c57000648.JPG)

**Comment by LaszloLajosT** [comment]
Hi,

Maybe you don't have your import :
import android.view.View.OnClickListener;

Or you have sync issue. In that case, clean your project(Menu-> Built-> clean project) and rebuilt it or run your app.

Or:
Under android studio there is a magic command which is ALT+ENTER it will propose you multiple solutions, you can try one.

**Comment by arsalanahmad4** [comment]
I am also getting a similar kind of problem. The code runs perfectly fine but it is not playing any media file neither it is displaying the toast message.

**Comment by SudKul** [comment]
Hey @arsalanahmad4 
Try the code in https://github.com/udacity/ud839_Miwok/pull/213 from @LaszloLajosT
