### ISSUE TITLE
simply nothing works

### ISSUE THREAD

**Issue by ta3pks** [udacity/ud839_Miwok#185]
![image](https://user-images.githubusercontent.com/9097437/75934818-08dd1280-5e97-11ea-8712-0ba1540813c8.png)

**Comment by sleepingpiggy67** [comment]
I have the exact same issue
my log says
Gradle sync failed: Don't know how to build models for org.gradle.tooling.internal.gradle.DefaultGradleBuild@23eb25e5

**Comment by ta3pks** [comment]
course quality is really amazing but when it comes to examples nothing works I ended up writing the thing by myself from scratch

**Comment by sleepingpiggy67** [comment]
I.... am not confident enough to write the whole thing from scratch. Did you change anything other than the xml file?

**Comment by ta3pks** [comment]
@sleepingpiggy67 I didnt exactly write the miwok app I just repeated the concept in a much simpler way skipping all the pictures and stuff since I know already how to add ImageViews Also I used kotlin instead of Java which is really much nicer and android studio writes the most of the code anyways just give it a go

**Comment by SudKul** [comment]
We have updated all branches to use Gradle 7.x, SDK API level 31, and AndroidX dependencies. New learners can use these steps:
- Fork this repository to your Github account.
- Open Android Studio 3.2.x+ in your local machine.
- We recommend you to use the [Version Control System](https://developer.android.com/studio/intro#version_control_basics)(VCS) in your Android Studio 3.2.x+ IDE to clone the repository directly in your IDE.
- You may have to use the File > Settings > Version Control (VCS) menu option to set up Git settings.
- Refer to this [IntelliJ document](https://www.jetbrains.com/help/idea/version-control-integration.html) for details.
- Working with VCS will make it easy for you to push your updates or switch between branches to your remote repository in Github.
