### ISSUE TITLE
Incremental java compilation is an incubating feature.

### ISSUE THREAD

**Issue by sleepingpiggy67** [udacity/ud839_Miwok#187]
I imported the file and fixed several errors but the log is now showing
Incremental java compilation is an incubating feature.
BUILD SUCCESSFUL
Total time: 12.018 secs
and nothing I do seems to be working

**Comment by ghost** [comment]
did this issue get solved?.....i am also facing the same isssue

**Comment by mithilp11** [comment]
same pro

**Comment by EXFFOO56566** [comment]
first make sure you have set your NDK path to the correct directory in the properties file.

and if you check you event log you should have this error: Gradle sync failed: Unsupported method: SyncIssue.getMultiLineMessage().
				The version of Gradle you connect to does not support that method.
				To resolve the problem you can change/upgrade the target version of Gradle you connect to.
				Alternatively, you can ignore this exception and read other information from the model.
				Consult IDE log for more details (Help | Show Log) (56 s 468 ms)

no worries here follow these steps: 
(1) set the class-path in your build.gradle to  'com.android.tools.build:gradle:3.0.1'

(2) set the distribution URL in your gradle wrapper properties to https\://services.gradle.org/distributions/gradle-4.1-all.zip

(3) then set the build tools version in your build.gradle (module:app)  to '25.0.0'  sync the project and  something like "Add google Maven repository and sync project" should appear, click on that and click on "do refactor" button when the dialog comes up, your project should sync properly. thumbs up if this helped ya get passed that.

also side note I'm using Android studio version  4.11.

from the screenshot below you can see this resolved the issue, i can"t push the project to github just yet but when i do I'll update this comment with the link.
![Screenshot - 10_4_2021 , 7_11_35 PM](https://user-images.githubusercontent.com/83840753/135949893-ea252e74-f903-45dc-8b21-08b15bb6858b.jpg)

**Comment by SudKul** [comment]
We recommend using https://knowledge.udacity.com/  platform for discussions so that mentors can chime in, and new learners can have visibility. 
Should you (or any learner) need help on individual issues, use the https://knowledge.udacity.com/ platform to discuss with our experienced mentors.
