### ISSUE TITLE
App closes upon updating the NumbersActivity

### ISSUE THREAD

**Issue by waveboy14** [udacity/ud839_Miwok#19]
What am I doing wrong? I have updated the complete NumbersActivity, following the show me the answer clip, but it doesn't resemble the final code, nor does it work. I had a crash upon opening the NumbersActivity which I solved with an If statement mMediaPlayer != null and now I can open the activity, but no sound plays and hitting it a couple of times, it shuts down.

Below my code:

package com.example.android.miwok;

import android.content.Context;
import android.media.AudioManager;
import android.media.MediaPlayer;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ListView;
import java.util.ArrayList;

public class NumbersActivity extends AppCompatActivity {

    // Handles playback of all the sound files
    private MediaPlayer mMediaPlayer;
    //Handles audio focus when playing a sound file
    private AudioManager mAudioManager;

    private AudioManager.OnAudioFocusChangeListener mOnAudioFocusChangeListener =
            new AudioManager.OnAudioFocusChangeListener() {
                @Override
                public void onAudioFocusChange(int focusChange) {
                    // || = "or"
                    if (focusChange == AudioManager.AUDIOFOCUS_LOSS_TRANSIENT ||
                            focusChange == AudioManager.AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK) {
                        /* The AUDIOFOCUS_LOSS_TRANSIENT case means we've lost audio focus for a
                        * short amount of time. The AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK case means
                        * our app is allowed to continue playing sound but at a lower volume. We want
                        * both cases the same way because our app is playing short sound files.*/
                        // Pause playback and reset player.
                        mMediaPlayer.pause();
                        // To restart the audiofile from the beginning, instead of resume playback
                        mMediaPlayer.seekTo(0);

                          // Pause playback
                    } else if (focusChange == AudioManager.AUDIOFOCUS_GAIN) {
                        // The AUDIOFOCUS_GAIN case means we have regained focus and can resume playback
                        mMediaPlayer.start();
                    } else if (focusChange == AudioManager.AUDIOFOCUS_LOSS) {
                        // AUDIOFOCUS_LOSS means we've lost audiofocus & should stop playback and
                        // clean up resources
                        releaseMediaPlayer();
                    }
                }
            };

    //This listener gets triggered when the {@link MediaPlayer} has completed playing the audio file
    private MediaPlayer.OnCompletionListener mCompletionListener = new MediaPlayer.OnCompletionListener() {

       public void onCompletion(MediaPlayer mp) {
            releaseMediaPlayer();
       }
    };

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.word_list);

        // Create and setup the {@link AudioManager} to request audio focus
        mAudioManager = (AudioManager) getSystemService(Context.AUDIO_SERVICE);

        // Create a list of words
        final ArrayList<Word> words = new ArrayList<Word>();
        words.add(new Word("one", "lutti",R.drawable.number_one, R.raw.number_one));
        words.add(new Word("two", "otiiko",R.drawable.number_two, R.raw.number_two));
        words.add(new Word("three", "tolookosu",R.drawable.number_three, R.raw.number_three));
        words.add(new Word("four", "oyyisa",R.drawable.number_four, R.raw.number_four));
        words.add(new Word("five", "massokka",R.drawable.number_five, R.raw.number_five));
        words.add(new Word("six", "temmokka",R.drawable.number_six, R.raw.number_six));
        words.add(new Word("seven", "kenekaku",R.drawable.number_seven, R.raw.number_seven));
        words.add(new Word("eight", "kawinta",R.drawable.number_eight, R.raw.number_eight));
        words.add(new Word("nine", "wo'e",R.drawable.number_nine, R.raw.number_nine));
        words.add(new Word("ten", "na'aacha",R.drawable.number_ten, R.raw.number_ten));

        // Create an {@link WordAdapter}, whose data source is a list of {@link Word}s. The
        // adapter knows how to create list items for each item in the list
        // The simple_list_item_1.xml layout resource defined in the Android framework is not used.
        WordAdapter adapter = new WordAdapter(this, words, R.color.category_numbers);

        // Find the {@link ListView} object in the view hierarchy of the {@link Activity}.
        // There should be a {@link ListView} with the view ID called list, which is declared in the
        // word_list.xml file.
        ListView listView = (ListView) findViewById(R.id.list);

        // Make the {@link ListView} use the {@link WordAdapter} we created above, so that the
        // {@link ListView} will display list items for each {@link Word} in the list.
        listView.setAdapter(adapter);

        // Set a click listener to play the audio when the list item is clicked on
        listView.setOnItemClickListener(new AdapterView.OnItemClickListener(){
            @Override
            public void onItemClick(AdapterView<?> adapterView, View view, int position, long l) {
                //Get the {@link Word} object at the given position the user clicked on
                Word word = words.get(position);
                // Release the media player if it currently exists, to play a different sound file
                releaseMediaPlayer();

                // Request audio focus for playback
                int result = mAudioManager.requestAudioFocus(mOnAudioFocusChangeListener,
                        // Use the music stream.   // Request permanent focus.
                        AudioManager.STREAM_MUSIC, AudioManager.AUDIOFOCUS_GAIN_TRANSIENT);
                // Start the audio file
                mMediaPlayer.start();

                if (result == AudioManager.AUDIOFOCUS_REQUEST_GRANTED) {
                    if (mMediaPlayer != null) {
                        // Stetup a listener on the media player to stop and release player when finished playing
                        mMediaPlayer.setOnCompletionListener(mCompletionListener);
                            // We have audio focus now
                            // Create + setup the {@link Mediaplayer} for the audio resource for the current word
                            mMediaPlayer = MediaPlayer.create(NumbersActivity.this, word.getAudioResourceId());
                            // Start the audio file
                            mMediaPlayer.start(); //No need to call prepare(), create does that for you
                            // Setup a listener on the media player to stop and release it once sound has finished playing
                            mMediaPlayer.setOnCompletionListener(mCompletionListener);}
                    }
            }
        });
    }
    @Override
    protected void onStop() {
        super.onStop();
        // When the activity stops, release media player resources to stop playing sounds
        releaseMediaPlayer();
    }
    //Clean up the media player by releasing its resources.
    private void releaseMediaPlayer() {
        // If the media player is not null, then it may be currently playing a sound.
        if (mMediaPlayer != null) {
            // Regardless of the current state of the media player, release its resources
            // because we no longer need it.
            mMediaPlayer.release();

            // Set the media player back to null. For our code, we've decided that
            // setting the media player to null is an easy way to tell that the media player
            // is not configured to play an audio file at the moment.
            mMediaPlayer = null;

            // Regardless of whether or not we were granted audio focus, abandon is. This also
            // unregisters the AudioFocusChangeListener so we don't get anymore callbacks
            mAudioManager.abandonAudioFocus(mOnAudioFocusChangeListener);

        }
    }
}

**Comment by waveboy14** [comment]
Error in logcat:

AndroidRuntime: FATAL EXCEPTION: main
                                                                         Process: com.example.android.miwok, PID: 4253
                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaPlayer.start()' on a null object reference
                                                                             at com.example.android.miwok.NumbersActivity$3.onItemClick(NumbersActivity.java:107)

**Comment by vcctu85** [comment]
@waveboy14 there are a couple of differences between your code and the final code. You should start the audio file after you compare the result instead of before. Also you are missing a few things at the end of your releaseMediaPlayer(). Let me know if that helps!

**Comment by Kvaibhav01** [comment]
@waveboy14 try to compare your code with [this (final code) one](https://github.com/udacity/ud839_Miwok/blob/lesson-four/app/src/main/java/com/example/android/miwok/NumbersActivity.java).

**Comment by johnshea** [comment]
Issue creator has not responded.
