### ISSUE TITLE
472472020 this is how i fix the build problems.

### ISSUE THREAD

**Issue by csa3902** [udacity/ud839_Miwok#191]
**copy and paste this code into build.gradle(project)**

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        google()
        maven {
            url 'https://maven.google.com'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.6.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        google()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**then copy and paste this code into build.gradle(project)**

apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion '27.0.3'

    defaultConfig {
        applicationId "com.example.android.miwok"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation "com.android.support:appcompat-v7:26.1.0"
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support:support-v4:26.1.0'
    implementation 'com.android.support:design:26.1.0'
}

**then sync gradle**

**Comment by sakshamg19** [comment]
I am getting an error : could not find method google() for arguments[] on repository container. Plz help.

**Comment by csa3902** [comment]
Did you figure it out yet? I can try to help. I changed the program and upgraded to androidx this does work I can share it if you need it I can post to github let me know I will try and watch my email more closely  thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by SudKul** [comment]
The workaround above is not needed any longer. 
We have updated all branches to use Gradle 7.x, SDK API level 31, and AndroidX dependencies.
