### ISSUE TITLE
Just downloaded project and:

### ISSUE THREAD

**Issue by turok08** [udacity/ud839_Miwok#193]
java.lang.IllegalStateException: failed to find target with hash string 'android-23' in: C:\Users\acer\AppData\Local\Android\Sdk
ERROR: failed to find target with hash string 'android-23' in: C:\Users\acer\AppData\Local\Android\Sdk

**Comment by LaszloLajosT** [comment]
Hi,

Here is a similar issue on  [StackOverflow:](https://stackoverflow.com/questions/40457524/failed-to-find-target-with-hash-string-android-25)

Two ways to fix it:

1.  Change your Target SDK to your current installed SDK ( In Android Studio: Left side on your project, you should see "Grandle Scripts". Open it -> build.grandle(Module:app) -> 
find this line:
`targetSdkVersion 29`  or whatever number is. Change it to your installed SDK level.
 
OR

2.  Install the missing platform(SDK) with SDK Manager in Android Studio.

**Comment by SudKul** [comment]
Thanks, @LaszloLajosT
