### ISSUE TITLE
PROBLEM IN MAIN ACTIVITY

### ISSUE THREAD

**Issue by shivani-jariwala** [udacity/ud839_Miwok#195]
![image](https://user-images.githubusercontent.com/64823330/82368118-81815300-9a32-11ea-913f-8f5a2a19d6d7.png)
Please help me soon. I have been trying hard on it since 2 days and still couldn't find any solution.

**Comment by andy6809** [comment]
import android.support.v7.app.AppCompatActivity;

**Comment by shivani-jariwala** [comment]
THANK YOU @andy6809

**Comment by andy6809** [comment]
Maybe try this:

https://www.dev2qa.com/how-to-auto-import-all-class-in-android-studio/
