### ISSUE TITLE
FAILURE: Build failed with an exception. Pls help :( I got this error

### ISSUE THREAD

**Issue by joa-kenit** [udacity/ud839_Miwok#196]
FAILURE: Build failed with an exception.
01:45:45.282 [ERROR] [org.gradle.BuildExceptionReporter] 
01:45:45.282 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
01:45:45.282 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred configuring project ':app'.
01:45:45.282 [ERROR] [org.gradle.BuildExceptionReporter] > Could not resolve all dependencies for configuration ':app:_debugCompile'.
01:45:45.282 [ERROR] [org.gradle.BuildExceptionReporter]    > Could not find com.android.support:appcompat-v7:23.3.0.
01:45:45.283 [ERROR] [org.gradle.BuildExceptionReporter]      Searched in the following locations:
01:45:45.283 [ERROR] [org.gradle.BuildExceptionReporter]          https://jcenter.bintray.com/com/android/support/appcompat-v7/23.3.0/appcompat-v7-23.3.0.pom
01:45:45.283 [ERROR] [org.gradle.BuildExceptionReporter]          https://jcenter.bintray.com/com/android/support/appcompat-v7/23.3.0/appcompat-v7-23.3.0.jar
01:45:45.284 [ERROR] [org.gradle.BuildExceptionReporter]      Required by:
01:45:45.284 [ERROR] [org.gradle.BuildExceptionReporter]          ud839_Miwok-lesson-one:app:unspecified
01:45:45.284 [ERROR] [org.gradle.BuildExceptionReporter]    > Could not find com.android.support:support-v4:23.3.0.
01:45:45.285 [ERROR] [org.gradle.BuildExceptionReporter]      Searched in the following locations:
01:45:45.285 [ERROR] [org.gradle.BuildExceptionReporter]          https://jcenter.bintray.com/com/android/support/support-v4/23.3.0/support-v4-23.3.0.pom
01:45:45.286 [ERROR] [org.gradle.BuildExceptionReporter]          https://jcenter.bintray.com/com/android/support/support-v4/23.3.0/support-v4-23.3.0.jar
01:45:45.286 [ERROR] [org.gradle.BuildExceptionReporter]      Required by:
01:45:45.287 [ERROR] [org.gradle.BuildExceptionReporter]          ud839_Miwok-lesson-one:app:unspecified
01:45:45.287 [ERROR] [org.gradle.BuildExceptionReporter]    > Could not find com.android.support:design:23.3.0.
01:45:45.287 [ERROR] [org.gradle.BuildExceptionReporter]      Searched in the following locations:
01:45:45.287 [ERROR] [org.gradle.BuildExceptionReporter]          https://jcenter.bintray.com/com/android/support/design/23.3.0/design-23.3.0.pom
01:45:45.288 [ERROR] [org.gradle.BuildExceptionReporter]          https://jcenter.bintray.com/com/android/support/design/23.3.0/design-23.3.0.jar
01:45:45.288 [ERROR] [org.gradle.BuildExceptionReporter]      Required by:
01:45:45.288 [ERROR] [org.gradle.BuildExceptionReporter]          ud839_Miwok-lesson-one:app:unspecified
01:45:45.288 [ERROR] [org.gradle.BuildExceptionReporter]

**Comment by Mohammed-Aman** [comment]
same issue

**Comment by rana2-3** [comment]
me too

**Comment by zakaria3698** [comment]
ME TO

**Comment by shivamag00** [comment]
In the Build Logs 

> FAILURE: Build failed with an exception.
> 01:45:45.282 [ERROR] [org.gradle.BuildExceptionReporter]
> 01:45:45.282 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
> 01:45:45.282 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred configuring project ':app'.
> 01:45:45.282 [ERROR] [org.gradle.BuildExceptionReporter] > Could not resolve all dependencies for configuration ':app:_debugCompile'.
> 01:45:45.282 [ERROR] [org.gradle.BuildExceptionReporter] > Could not find com.android.support:appcompat-v7:23.3.0.
> 01:45:45.283 [ERROR] [org.gradle.BuildExceptionReporter] Searched in the following locations:
> 01:45:45.283 [ERROR] [org.gradle.BuildExceptionReporter] https://jcenter.bintray.com/com/android/support/appcompat-v7/23.3.0/appcompat-v7-23.3.0.pom
> 01:45:45.283 [ERROR] [org.gradle.BuildExceptionReporter] https://jcenter.bintray.com/com/android/support/appcompat-v7/23.3.0/appcompat-v7-23.3.0.jar
> 01:45:45.284 [ERROR] [org.gradle.BuildExceptionReporter] Required by:
> 01:45:45.284 [ERROR] [org.gradle.BuildExceptionReporter] ud839_Miwok-lesson-one:app:unspecified
> 01:45:45.284 [ERROR] [org.gradle.BuildExceptionReporter] > Could not find com.android.support:support-v4:23.3.0.
> 01:45:45.285 [ERROR] [org.gradle.BuildExceptionReporter] Searched in the following locations:
> 01:45:45.285 [ERROR] [org.gradle.BuildExceptionReporter] https://jcenter.bintray.com/com/android/support/support-v4/23.3.0/support-v4-23.3.0.pom
> 01:45:45.286 [ERROR] [org.gradle.BuildExceptionReporter] https://jcenter.bintray.com/com/android/support/support-v4/23.3.0/support-v4-23.3.0.jar
> 01:45:45.286 [ERROR] [org.gradle.BuildExceptionReporter] Required by:
> 01:45:45.287 [ERROR] [org.gradle.BuildExceptionReporter] ud839_Miwok-lesson-one:app:unspecified
> 01:45:45.287 [ERROR] [org.gradle.BuildExceptionReporter] > Could not find com.android.support:design:23.3.0.
> 01:45:45.287 [ERROR] [org.gradle.BuildExceptionReporter] Searched in the following locations:
> 01:45:45.287 [ERROR] [org.gradle.BuildExceptionReporter] https://jcenter.bintray.com/com/android/support/design/23.3.0/design-23.3.0.pom
> 01:45:45.288 [ERROR] [org.gradle.BuildExceptionReporter] https://jcenter.bintray.com/com/android/support/design/23.3.0/design-23.3.0.jar
> 01:45:45.288 [ERROR] [org.gradle.BuildExceptionReporter] Required by:
> 01:45:45.288 [ERROR] [org.gradle.BuildExceptionReporter] ud839_Miwok-lesson-one:app:unspecified
> 01:45:45.288 [ERROR] [org.gradle.BuildExceptionReporter]

In the build logs,after compiling, you must be see  an option to add Google Maven repository. Please Click on that so that it can download the required files from Google's Maven Repository. That should solve your issue. If it doesn't, please be sure to inform me...

**Comment by ridwanbinsaad** [comment]
Please mates can anyone help I still have these errors  even after doing the following **( Please Click on that so that it can download the required files from Google's Maven Repository. That should solve your issue.)
![Screenshot (1)](https://user-images.githubusercontent.com/58343797/87252102-d65cab00-c470-11ea-90ab-4b244056466a.png)
![Screenshot (2)](https://user-images.githubusercontent.com/58343797/87252106-dd83b900-c470-11ea-8842-489336c2868c.png)

**Comment by shivamag00** [comment]
> Please mates can anyone help I still have these errors even after doing the following **( Please Click on that so that it can download the required files from Google's Maven Repository. That should solve your issue.)
> ![Screenshot (1)](https://user-images.githubusercontent.com/58343797/87252102-d65cab00-c470-11ea-90ab-4b244056466a.png)
> ![Screenshot (2)](https://user-images.githubusercontent.com/58343797/87252106-dd83b900-c470-11ea-8842-489336c2868c.png)

Send a screenshot of your gradle files of both project and app

**Comment by ridwanbinsaad** [comment]
> > Please mates can anyone help I still have these errors even after doing the following **( Please Click on that so that it can download the required files from Google's Maven Repository. That should solve your issue.)
> > ![Screenshot (1)](https://user-images.githubusercontent.com/58343797/87252102-d65cab00-c470-11ea-90ab-4b244056466a.png)
> > ![Screenshot (2)](https://user-images.githubusercontent.com/58343797/87252106-dd83b900-c470-11ea-8842-489336c2868c.png)
> 
> Send a screenshot of your gradle files of both project and app

Thanks I got it fixed after working on it for hours.
