### ISSUE TITLE
I got the solution

### ISSUE THREAD

**Issue by joa-kenit** [udacity/ud839_Miwok#197]
So, I fixed it by copy and paste graddle scripts from previous apps that actually worked :)

**Comment by RusuAlexandru91** [comment]
Did the same and worked . Ty :)

**Comment by Jignesh220** [comment]
it also works for me. ty 👍

**Comment by Tauseef18** [comment]
Can you guyz guide me from where to get that scripts ?

**Comment by SudKul** [comment]
We have updated all branches to use Gradle 7.x, SDK API level 31, and AndroidX dependencies. 
You can see the "Lessno-five" branch for a solution.
