### ISSUE TITLE
Having issue importing file

### ISSUE THREAD

**Issue by wha2les** [udacity/ud839_Miwok#2]
So i followed direction of the video, and I imported the file into Android Stuido, but I am unable to run the app and I get a gradle not synced issue... I tried multiple time to resolve the issue and I also deleted files and re-imported the file and still get same issues. Assistance would be greatly appreciated.

**Comment by TriplEight** [comment]
Same situation over here. Import finishes like that: http://i.imgur.com/ossT8A2.png

**Comment by TriplEight** [comment]
OK, I've found out how to fix it:
1. Fork this repository to your GitHub account.
2. Open Android Studio.
3. File - New - Project from version control - GitHub
4. Paste a link from your repository of the forked Miwok app, push Clone.
5. Agree with everything and update everything it asks.
6. Launch on the phone.
Udacity, please change your instructions.

**Comment by wha2les** [comment]
I get this error when trying to Open new project from version control-GitHub: "Cannot run program "git.exe": CreateProcess error=2, The system cannot find the file specified"

**Comment by wha2les** [comment]
I followed your instruction, and i get this error when I am importing: "SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.  Consult IDE log for more details (Help | Show Log)"

**Comment by TriplEight** [comment]
I was getting the same error when I tried to import the original project from Udacity (this) repository.
But when I forked it to my own repo, it worked like I described.
I don't know maybe try pushing Test and mention the existing directory in import from GitHub dialogue: http://i.imgur.com/0flUajH.png
Also in further questions of the dialogue choose some existing gradle and API version.
Also probably this can help you: http://stackoverflow.com/questions/32177349/sdk-location-not-found
Did your IDE work previously?

**Comment by wha2les** [comment]
I never had any issues earlier, but this is the first time I ever tried to importing an entire project.

**Comment by byhazellaw** [comment]
I didn't have the SDK issue but I am missing the entire drawable folder, thus not able to render anything at all. Any idea?

**Comment by Sinapse87** [comment]
Hi, if you have a gradle problem it means that you probably "opened" the project rather than "new/import project"
If you have an sdk  problem, it means that your sdk it is not properly setup into your IDE. Go in preferences and type sdk. Under Android SDK give the right path for your sdk. A file called local.properties will automatically be generated under your gradle scripts source folder with the following content:

ndk.dir=/Users/x/Library/Android/sdk/ndk-bundle
sdk.dir=/Users/x/Library/Android/sdk

Lemme know!

**Comment by asamirel** [comment]
This solved the issue for me : http://stackoverflow.com/questions/27951027/errorcould-not-run-build-action-using-gradle-installation-c-program-files-and

-The idea is simply we are using new version of android studio sdk, and these projects built using older android sdk versions so we have to remove the gradle file and let android studio installs the new one for us.

**Comment by nkairbayev** [comment]
The method suggested by TriplEight, that uses the GitHub cloning worked out for me!

**Comment by Hedson** [comment]
Another method, works for me:
1) Create new standard empty project
2) Close project
3) Delete everything inside our new project ProjectName/app folder
4) Copy & paste to our new project app folder everything from MiwokiAppName\app folder

**Comment by karsoumik27** [comment]
is it suppose to download something from the web?? after importing??

**Comment by rydarg** [comment]
So I faced a similar issue, with very similar error messages. I tried copy pasting the contents from one folder to another as @Hedson suggested it, but it didnt work and managed to bog down Android Studio to a crawl. After a few tries, I went to C:\Users<UserName> and cleared the .gradle folder. and then I imported the code as @TriplEight mentioned in an earlier post. It's working for now. Thanks!

**Comment by owolabiezekiel** [comment]
the thing i did was to make sure that i unzipped the file in to the android studio projects folder. then when importing the project, make sure you click on the miwok folder itself and make sure you are connected to the internet because there might be gradle dependency issues and sdk upgrade issues. thanks

**Comment by aamick01** [comment]
Thanks TriplEight!  It worked perfectly.  Udacity should really add this to their instructions.  I will inform them.

**Comment by vcctu85** [comment]
Closing this issue because student's questions were answered, and instructions on site were updated accordingly.

**Comment by Nejdanchik** [comment]
Hedson, it's a brilliant idea! Simple and brilliant! I spent nearly 4 hours trying to import this project. And your method worked. Thanks a lot!

Another method, works for me:

Create new standard empty project
Close project
Delete everything inside our new project ProjectName/app folder
Copy & paste to our new project app folder everything from MiwokiAppName\app folder

**Comment by gpnavin86** [comment]
Fork and import did work but the preview does not work, can anyone help?

**Comment by ocephraim** [comment]
Thanks @Hedson. Life saver.


@gpnavin86  
1) replace the dependencies{} in your Gradle Scripts >> build.gradle(Module App) file, with that from a previously built project that renders perfectly fine.
2) in the same file as above, update the tragetSDKVersion, buildToolsVersion and compileSDKVersion to the current one your Android Studio supports.

Note: This worked for me after following @Hedson's recommendation.

**Comment by ocephraim** [comment]
Thanks @Hedson. Life Saver

**Comment by nyk47** [comment]
@Hedson thanks. it worked .

**Comment by PremSujan** [comment]
Thank u very much @Nejdanchik 
 U saved me a lot of time

**Comment by HRGiri** [comment]
Thanks @Hedson!!!

**Comment by mokshith28** [comment]
Thanks @Hedson Worked for me. Amazing idea!
