### ISSUE TITLE
Failed to resolve: org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler:6.5.1:

### ISSUE THREAD

**Issue by Uday-AK** [udacity/ud839_Miwok#203]

**Comment by Uday-AK** [comment]
implementation 'org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler:6.5.1'

**Comment by SudKul** [comment]
This issue will not arise any longer. 
We have updated all branches to use Gradle 7.x, SDK API level 31, and AndroidX dependencies.
