### ISSUE TITLE
Errore

### ISSUE THREAD

**Issue by Adom75** [udacity/ud839_Miwok#204]
i tried many sulotion, none  of them is working.
can you make a new git files that updated ?

**Comment by neelangshu007** [comment]
Download the ZIP Folder or Clone the repo and then upgrade the gradel

**Comment by SudKul** [comment]
Hey @neelangshu007 
- We recommend you to use the [Version Control System](https://developer.android.com/studio/intro#version_control_basics)(VCS) in your Android Studio 3.2.x+ IDE to clone the repository directly in your IDE.
- You may have to use the File > Settings > Version Control (VCS) menu option to set up Git settings.
- Refer to this [IntelliJ document](https://www.jetbrains.com/help/idea/version-control-integration.html) for details.
- Working with VCS will make it easy for you to push your updates or switch between branches to your remote repository in Github.
