### ISSUE TITLE
Failed to find build tools revision 29.0.2 - Android Studio

### ISSUE THREAD

**Issue by devjaiye** [udacity/ud839_Miwok#205]
If you encounter this issue. simply go this website to download the required build tool for your project  https://androidsdkmanager.azurewebsites.net/Buildtools

Step 2 >> Extract the downloaded file

Step 3 >> Locate the build-tools folder inside your SDK e.g 
 **(C:\Android\Sdk\build-tools)**

Step 4 >> Paste the folder in the **build-tools** In my case, The default folder name was **"Android-10"** after I extracted the file but I change it to **29.0.2** since that's the issue I wanted to solve 

Step 5 >> Rebuild your project :) .. Done!
 

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/Rcaki.png

**Comment by Pavanpalve** [comment]
this issue is due to we are trying opening too old projects on latest android studio

**Comment by SudKul** [comment]
We have updated all branches to use Gradle 7.x, SDK API level 31, and AndroidX dependencies.
