### ISSUE TITLE
This will help you out a little

### ISSUE THREAD

**Issue by SyedAtifAli** [udacity/ud839_Miwok#206]
**This is not an issue but if someone is having the same issues with v7.appComa....... or a red swiggy line under main_activity.java file you can do the following**

gradle scripts>>build gradel(module:app)

under dependencies
cut everything and paste the following codes!

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    //noinspection GradleCompatible
    implementation "com.android.support:support-v4:23.1.1"
    //noinspection GradleCompatible
    implementation "com.android.support:appcompat-v7:23.1.1"
    implementation "com.android.support:support-annotations:23.1.1"
    }

and check the Build tab on the bottom left corner for more isssues

if this didnt work out for you you can always undo things!!

**Comment by SudKul** [comment]
Thanks, @SyedAtifAli 
Learners will not face the issue above. 
We have updated all branches to use Gradle 7.x, SDK API level 31, and AndroidX dependencies.
