### ISSUE TITLE
Failed to resolve: com.android.support:support-v4:23.0.0 and other dependencies

### ISSUE THREAD

**Issue by sapkalemayur86** [udacity/ud839_Miwok#207]
in build.gradle file
change dependencies to

..dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
//noinspection GradleCompatible
    implementation "com.android.support:support-v4:23.1.1"
//noinspection GradleCompatible
    implementation "com.android.support:appcompat-v7:23.1.1"
    implementation "com.android.support:support-annotations:28.0.0"
}

and in build.gradle(project UD839.....) file
in the repositories  make changes like following 

repositories {
        jcenter()
        maven { url 'https://maven.google.com' }
    } 

that's all . if it does not  work you can always undo it. all the best.

**Comment by nitish778191** [comment]
![dd](https://user-images.githubusercontent.com/68564476/106322267-9ab5f100-629b-11eb-8359-7eeaf1806a84.png)
please help  me out guys t0 resolve this issue

**Comment by SudKul** [comment]
@sapkalemayur86 
I am assuming you may not need assistance at the moment. 

Should you (or any learner) need help on individual issues, we recommend using the https://knowledge.udacity.com/ platform to discuss with our experienced mentors.
