### ISSUE TITLE
I feel silly.

### ISSUE THREAD

**Issue by justinhern868** [udacity/ud839_Miwok#21]
Where is the zip file option?

**Comment by owolabiezekiel** [comment]
i also cant find it here

**Comment by justinhern868** [comment]
Got to code tab, go to the right where it says clone or download. 
Then you should see the option to download zip.
I hope that helps, I had to figure this out on my own.

**Comment by owolabiezekiel** [comment]
the clone/download button isn't working. tried that a million times

**Comment by patildurgesh21** [comment]
For me also, the clone/ download button is not working .

**Comment by justinhern868** [comment]
Did you try the drop down button?

**Comment by vcctu85** [comment]
Hi @owolabiezekiel @patildurgesh21 ! Were you able to get the clone/download button to work? If not, please comment a screenshot, and I will do my best to help you.
Vicky

**Comment by Kvaibhav01** [comment]
Click these links if you are not able to download from that button: [Lesson one](https://codeload.github.com/udacity/ud839_Miwok/zip/lesson-one), [Lesson ](https://codeload.github.com/udacity/ud839_Miwok/zip/lesson-two)2, [Lesson 3](https://codeload.github.com/udacity/ud839_Miwok/zip/lesson-three), [Lesson ](https://codeload.github.com/udacity/ud839_Miwok/zip/lesson-four)4 and [Lesson ](https://codeload.github.com/udacity/ud839_Miwok/zip/lesson-five)5

**Comment by owolabiezekiel** [comment]
oh thanks so much @vcctu85 its finally worked

**Comment by vcctu85** [comment]
Closing this issue because student's question was answered.
