### ISSUE TITLE
ANDROID STUDIO OFFLINE

### ISSUE THREAD

**Issue by Josivo** [udacity/ud839_Miwok#214]
I have Downloaded Android studio, Google maven dependencies, sdk tool packages ,gradle plugin from their official website. 
Now i am stuck with the installation procedure since i want to install these and build the project offline ! Where do i place google maven dependencies and other downloaded packages in studio??
Please help.. 
I don't want to use internet since it's very slow and low data per day hence i downloaded offline packages

**Comment by holmesherlockhs** [comment]
You can't do this without the internet. Use a hotspot.
