### ISSUE TITLE
Gradle sync failed: Unsupported method: SyncIssue.getMultiLineMessage(). (Android Studio) and how I fixed it

### ISSUE THREAD

**Issue by Diver1rn** [udacity/ud839_Miwok#215]
Kept getting this error when I tried to import the file.  Several days of digging and a little luck later, learned about gradle versions and Android Gradle Plug in versions.  The numbers are not the same but they must correspond as per the table in this link:  [https://developer.android.com/studio/releases/gradle-plugin]()  After I got that then I had to go into the build.gradle file and change it to this.  My changes are annotated
`// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()//Add this
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'//change to this

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()//add this
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
`

and in the griddle-wrappers.properties file change
distributionUrl=https\://services.gradle.org/distributions/gradle-2.10-all.zip
to
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip

If you look at the table in the link you will see that the 4.1.0 in this build.gradle file line
classpath 'com.android.tools.build:gradle:4.1.0'
matches the 6.5-all in this gradle-wrapper.properties line
distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip

I didn't try it but I would imagine that as long as the numbers correspond to each other on the chart then it would work even if it weren't exactly these numbers.

Hope this helps someone else out.

**Comment by dhruvmendiratta6** [comment]
I have been at it for hours... Being a beginner I don't really understand the fix but it finally works! Thank you

**Comment by Diver1rn** [comment]
@dhruvmendiratta6 .  I'm pretty new also but best I can determine the code in the gradle-wrapper.properties file downloads a big zip file with a lot of information including the Android Studio plug ins.  The code in the build.gradle file identifies the Android Studio plug in to use.  So, you use the link to determine what Android Studio plug in is in each zip file and you just have to make sure they match.  Your welcome.  Glad it helped you out.

**Comment by Mazin1989** [comment]
I confirm the issue was fixed by making the below changes/additions in the following files:

    build.gradle

and

    gradle-wrapper.properties


In the `build.gradle` file I have added 

`        	maven {
            	url 'https://maven.google.com/'
            	name 'Google'
        		}`  in both the `buildscript` and `allprojects` just below `jcenter()` and changed the `classpath` to `classpath 'com.android.tools.build:gradle:4.1.0'`

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.1.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

and in the Gradle Properties I did the changes mentioned by @Diver1rn and changed distributionUrl=https\://services.gradle.org/distributions/gradle-**6.5**-all.zip

	#Mon Dec 28 10:00:20 PST 2015
	distributionBase=GRADLE_USER_HOME
	distributionPath=wrapper/dists
	zipStoreBase=GRADLE_USER_HOME
	zipStorePath=wrapper/dists
	distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip


Hope this helps all the others who are stuck and want to fix this issue with a copy and paste solution only.

**Comment by atharva137** [comment]
@Mazin1989 thanks man it really helped me

**Comment by chasmis03** [comment]
@dhruvmendiratta6  Thanks bro it really worked .
begin new to coding world i was unable to understand anything

**Comment by sanjarcode** [comment]
Here's my repo
https://github.com/sanjarcode/ud839_Miwok.git
Fully updated to run the app

**Comment by eraZora** [comment]
@Diver1rn  I was stuck for hours on this. thanks, man  :'))

**Comment by Hritik-del** [comment]
@Mazin1989  thanks a lot bro, have been stuck at this for weeks.

**Comment by Aman7400** [comment]
@Mazin1989 thanks mate it helped a lot 🙌

**Comment by herik-MD** [comment]
@Mazin1989 thank u so much....

**Comment by sandeshtukrul** [comment]
@Mazin1989 Thanks bro!!!

**Comment by debdhriti** [comment]
[](url)
![2021-01-18](https://user-images.githubusercontent.com/77495660/104885412-0b9d0500-598e-11eb-9383-e3cf5063a7ea.png)
due to these, the app isn't running as well
Why are these errors showing, please resolve..

**Comment by Diver1rn** [comment]
@debdhriti I'm an absolute beginner on android also but it looked like there was a backslash in the address.  This is what needs to be in the gradle properties file
distributionUrl=https://services.gradle.org/distributions/gradle-6.5-all.zip

**Comment by Rudra2201** [comment]
@Diver1rn  Thanks a lot!! It worked for me

**Comment by vedantbhatnagar53** [comment]
![Screenshot 2021-06-15 125923](https://user-images.githubusercontent.com/71769241/122011383-a5e86400-cdd9-11eb-92fd-e5b9dffe3876.jpg)
this problem is showing what to do next?

**Comment by Diver1rn** [comment]
Did you download the 6.5-all.zip and make the change listed below to the griddle-wrappers.properties file?

and in the griddle-wrappers.properties file change
distributionUrl=https://services.gradle.org/distributions/gradle-2.10-all.zip
to
distributionUrl=https://services.gradle.org/distributions/gradle-6.5-all.zip

**Comment by PranavSangave** [comment]
@Diver1rn Thank you so much, sir. It helps me a lot as a beginner.

**Comment by cgletras** [comment]
> Kept getting this error when I tried to import the file. Several days of digging and a little luck later, learned about gradle versions and Android Gradle Plug in versions. The numbers are not the same but they must correspond as per the table in this link: https://developer.android.com/studio/releases/gradle-plugin After I got that then I had to go into the build.gradle file and change it to this. My changes are annotated `// Top-level build file where you can add configuration options common to all sub-projects/modules.
> 
> buildscript { repositories { google()//Add this jcenter() } dependencies { classpath 'com.android.tools.build:gradle:4.1.0'//change to this
> 
> ```
>     // NOTE: Do not place your application dependencies here; they belong
>     // in the individual module build.gradle files
> }
> ```
> 
> }
> 
> allprojects { repositories { google()//add this jcenter() } }
> 
> task clean(type: Delete) { delete rootProject.buildDir } `
> 
> and in the griddle-wrappers.properties file change distributionUrl=https://services.gradle.org/distributions/gradle-2.10-all.zip to distributionUrl=https://services.gradle.org/distributions/gradle-6.5-all.zip
> 
> If you look at the table in the link you will see that the 4.1.0 in this build.gradle file line classpath 'com.android.tools.build:gradle:4.1.0' matches the 6.5-all in this gradle-wrapper.properties line distributionUrl=https://services.gradle.org/distributions/gradle-6.5-all.zip
> 
> I didn't try it but I would imagine that as long as the numbers correspond to each other on the chart then it would work even if it weren't exactly these numbers.
> 
> Hope this helps someone else out.

It helped. Thanks!

**Comment by SudKul** [comment]
This is help, @Diver1rn 
We will add this to the readme, under the (new) troubleshooting section.
