### ISSUE TITLE
Cannot Run Git runnerw.exe: CreateProcess failed with error 5: Access is denied.

### ISSUE THREAD

**Issue by hibazhd** [udacity/ud839_Miwok#218]
can someone please help me on how to open the project from vision control?

**Comment by SudKul** [comment]
These references may help:
- Use the [Version Control System](https://developer.android.com/studio/intro#version_control_basics)(VCS) in your Android Studio 3.2.x+ IDE to clone the repository directly in your IDE.
- You may have to use the File > Settings > Version Control (VCS) menu option to set up Git settings.
- Refer to this [IntelliJ document](https://www.jetbrains.com/help/idea/version-control-integration.html) for details.
- Working with VCS will make it easy for you to push your updates or switch between branches to your remote repository in Github.
