### ISSUE TITLE
Not able to clone

### ISSUE THREAD

**Issue by ShaunakKDatar** [udacity/ud839_Miwok#227]
I tried to follow the instructions given for a newer version of android studio
Yet every time i push clone, i get a error- unable to create destination directory.
Could you help me with this

**Comment by SudKul** [comment]
I am assuming you may not need assistance at the moment. 

Yet, for visitors, these references may help:
- We recommend you to use the [Version Control System](https://developer.android.com/studio/intro#version_control_basics)(VCS) in your Android Studio 3.2.x+ IDE to clone the repository directly in your IDE.
- You may have to use the File > Settings > Version Control (VCS) menu option to set up Git settings.
- Refer to this [IntelliJ document](https://www.jetbrains.com/help/idea/version-control-integration.html) for details.
- Working with VCS will make it easy for you to push your updates or switch between branches to your remote repository in Github.

**Comment by SudKul** [comment]
Should you (or any learner) need help on individual issues, we recommend using the https://knowledge.udacity.com/ platform to discuss with our experienced mentors.
