### ISSUE TITLE
Updated Miwok App 2021!

### ISSUE THREAD

**Issue by hamdi-bouasker** [udacity/ud839_Miwok#228]
Hi everyone,

I was several times frustrated because of the outdated Miwok app so I decided to make my life and others lives easier by coding new Miwok starter code fully updated to meet Android studio 2021. No more frustrations! Enjoy and happy coding 👍

Cheers 🙂

[Miwok App 2021](https://github.com/IT-Support-L2/Adapted-Miwok-App)

**Comment by Mohammed-Firasat-Hussain** [comment]
Thanks a lot! Finally can sleep in peace.

**Comment by hamdi-bouasker** [comment]
> Thanks a lot! Finally can sleep in peace.

Happy to help 🙂

**Comment by Rudra2201** [comment]
Thank you so much!!

**Comment by hamdi-bouasker** [comment]
you welcome

**Comment by Chandan-Bhadrala** [comment]
Thank you bro a lot. May you earn billions of dollars. it was Quite a frustrating Experience with a bit of new learning for last 5 hours. & finally just before loosing all hope, i found you.
Thanks a looooooooot.......

**Comment by hamdi-bouasker** [comment]
Happy to help 🙂

**Comment by yashj-7** [comment]
thankss a lottt .. nd i mean alottt .. i was just gonna quit nd i found your link ... you came as a blessing.. thank you man

**Comment by hamdi-bouasker** [comment]
happy to help 🙂 you welcome

**Comment by yashj-7** [comment]
> happy to help 🙂 you welcome

if u can ...i would really like to know what the main problem was ..

**Comment by hamdi-bouasker** [comment]
in brief there is 3 main problems:

1- Default Min SDK and Max SDK of the 2015 code are not the Default Min SDK and MAX SDK of Android Studio 2021

2- compileSdkVersion and buildToolsVersion of the starter code 2015 are not compatible with Android Studio 2021

3- And ESPECIALLY:

 androidx implementation 

HINT

Look to app/build.gradle of my code and the udacity starter code to find out the differences. 

Cheers 🙂

https://github.com/IT-Support-L2/Adapted-Miwok-App/blob/master/app/build.gradle

**Comment by yashj-7** [comment]
> in brief there is 3 main problems:
> 
> 1- Default Min SDK and Max SDK of the 2015 code are not the Default Min SDK and MAX SDK of Android Studio 2021
> 
> 2- compileSdkVersion and buildToolsVersion of the starter code 2015 are not compatible with Android Studio 2021
> 
> 3- And ESPECIALLY:
> 
> androidx implementation
> 
> HINT
> 
> Look to app/build.gradle of my code and the udacity starter code to find out the differences.
> 
> Cheers 🙂
> 
> https://github.com/IT-Support-L2/Adapted-Miwok-App/blob/master/app/build.gradle

thank you man.. thanks a lott.. :-))

**Comment by saiprasad-patil** [comment]
Hey! Could you help me with something?
In Android studio all my activities show the same lable as header.

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.android.miwok">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity
            android:name=".NumbersActivity"
            android:label="@string/category_numbers"
            android:parentActivityName=".MainActivity">
            
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value=".MainActivity"/>
        </activity>
        <activity
            android:name=".FamilyActivity"
            android:label="@string/category_family"
            android:parentActivityName=".MainActivity">
            
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value=".MainActivity"/>
        </activity>
        <activity
            android:name=".ColorsActivity"
            android:label="@string/category_colors"
            android:parentActivityName=".MainActivity">
            
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value=".MainActivity"/>
        </activity>
        <activity
            android:name=".PhrasesActivity"
            android:label="@string/category_phrases"
            android:parentActivityName=".MainActivity">
            
            <meta-data
                android:name="android.support.PARENT_ACTIVITY"
                android:value=".MainActivity"/>
        </activity>
    </application>

</manifest>`

thank you

**Comment by Avikarn** [comment]
thankyou so much man

**Comment by hamdi-bouasker** [comment]
> thankyou so much man

you welcome 🙂

**Comment by sudiptapradhan** [comment]
![image](https://user-images.githubusercontent.com/64891121/122774049-7f896380-d2c6-11eb-8efa-10b2c3d26e24.png)

Facing this problem. Can you help?

**Comment by Avikarn** [comment]
> ![image](https://user-images.githubusercontent.com/64891121/122774049-7f896380-d2c6-11eb-8efa-10b2c3d26e24.png)
> 
> Facing this problem. Can you help?

use this instead of arrayadapter   :
 WordAdapter adapter = new WordAdapter(this, words) ;

hope it helps :)


![image](https://user-images.githubusercontent.com/68471675/122777780-fecc6680-d2c9-11eb-9d9e-303e88ec7359.png)
@sudiptapradhan

**Comment by CoderxAbhi** [comment]
After seeing all the errors I didn't know what to do. Man you saved my life. Thank you so much!

**Comment by sudiptapradhan** [comment]
![image](https://user-images.githubusercontent.com/64891121/123253272-ed25d180-d50a-11eb-9543-4e7e7974c993.png)

Can anyone help me out with the error here
After going for the numbers activity, the app gets crashed.

And run tab shows this error but I don't understand what can i rectify

Can anyone help 

This is in reference to Android Basics: Multiscreen apps, Lesson 2

**Comment by Rogsahil10** [comment]
> Hi everyone,
> 
> I was several times frustrated because of the outdated Miwok app so I decided to make my life and others lives easier by coding new Miwok starter code fully updated to meet Android studio 2021. No more frustrations! Enjoy and happy coding 👍
> 
> Cheers 🙂
> 
> [Miwok App 2021](https://github.com/IT-Support-L2/Adapted-Miwok-App)

**Comment by mdparvez8** [comment]
I almost gave up on this course i literally spent 3 to 4 hours on fixing it. At last found this one thank You so much

**Comment by Swarn96** [comment]
**thankyou so so much.....**

**Comment by hamdi-bouasker** [comment]
> I almost gave up on this course i literally spent 3 to 4 hours on fixing it. At last found this one thank You so much 

happy to help 🙂

**Comment by hamdi-bouasker** [comment]
> **thankyou so so much.....**

happy to help 🙂

**Comment by phoeniXharsh** [comment]
> Hi everyone,
> 
> I was several times frustrated because of the outdated Miwok app so I decided to make my life and others lives easier by coding new Miwok starter code fully updated to meet Android studio 2021. No more frustrations! Enjoy and happy coding 👍
> 
> Cheers 🙂
> 
> [Miwok App 2021](https://github.com/IT-Support-L2/Adapted-Miwok-App)

**You're a life Saver**

**Comment by simarjeet30** [comment]
Thank you soo much ,I have been looking for this from last 3 days.

**Comment by yahayakayode** [comment]
Thank you for the good job, please how do you manage the color.xml, style.xml and themes.xml? as they all have similar contents.
Thank you.

**Comment by LuisArmando9** [comment]
Thank bro, good joob. You help me so so much.

**Comment by hamdi-bouasker** [comment]
you welcome bro, I will do the same for the weather app soon. Happy coding 🙂

**Comment by amangusain302** [comment]
bro, you are a hero, you save my time. I lose hope but then I found you, thanks a lot bro.

**Comment by SudKul** [comment]
Thanks, @IT-Support-L2 for suggesting the fixes. 
Letting new learners know that we have also updated and tested all branches to use Gradle 7.x, SDK API level 31, and AndroidX dependencies.

**Comment by hamdi-bouasker** [comment]
Actually I did not suggested the fixes, I fixed them all!

Actually udacity, coursera or any learning platform still didn't want to enforce a course update policy such as every 3 months. 

It is not acceptable to host a course which needs a back to time machine to meet old dependencies.

**Comment by Amrhany91** [comment]
I cannot find any java classes or anything @ MainActivity.java
please help me because Udacity Course Code is outdated, like FragmentPagerAdapter
