### ISSUE TITLE
HELP ME WITH THIS ERROR Ambiguous method call. Both findViewById (int) in AppCompatActivity and findViewById (int) in Activity match

### ISSUE THREAD

**Issue by Ahmadkaj** [udacity/ud839_Miwok#231]
Ambiguous method call. Both
findViewById
(int)
in AppCompatActivity and
findViewById
(int)
in Activity match

//MY build.gradle

apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.2'

    defaultConfig {
        applicationId "com.example.android.miwok"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support.constraint:constraint-layout:2.0.4'
    testImplementation'junit:junit:4.13.2'
    implementation'com.android.support:appcompat-v7:23.3.0'
    implementation 'com.android.support:support-v4:23.3.0'
    implementation'com.android.support:design:23.3.0'
}

**Comment by SudKul** [comment]
I am assuming you may not need assistance at the moment. 

Should you (or any learner) need help on individual issues, we recommend using the https://knowledge.udacity.com/ platform to discuss with our experienced mentors.
