### ISSUE TITLE
Could not initialize class com.android.sdklib.repositoryv2.AndroidSdkHandler

### ISSUE THREAD

**Issue by bikashroul99** [udacity/ud839_Miwok#234]
Could not initialize class com.android.sdklib.repositoryv2.AndroidSdkHandler

**Comment by shrutishreya108** [comment]
check if ur gradle version is right corresponding to ur gradle plugin version or not

**Comment by SudKul** [comment]
We have updated all branches to use Gradle 7.x, SDK API level 31, and AndroidX dependencies.
