### ISSUE TITLE
I believe I did everything as the instruction but there is a error showing unreachable statement. Am I the only one facing this?

### ISSUE THREAD

**Issue by Eshan133** [udacity/ud839_Miwok#239]
![Screenshot (55)](https://user-images.githubusercontent.com/86607719/124268696-9303bc80-db59-11eb-9779-1a977ba1aad0.png)

**Comment by piyush921** [comment]
You can't do anything after return the value. So, remove the return statement at line 24.

**Comment by Eshan133** [comment]
Thank you, It worked.
I also wanted to know, why it showed error when I did it exactly like instruction.
Is it because of a new update or something??

**Comment by piyush921** [comment]
No, it's about programming language. Please read some basics before you get hands on code. 
the return statement of a method is always written at the end of the method. See line 40, where you have returned a view object.

**Comment by Eshan133** [comment]
oh, I get it now.  Thank you very much. 
I will surely take up on your advice. Thank you ..
