### ISSUE TITLE
Could not initialize class com.android.sdklib.repositoryv2.AndroidSdkHandler error !!!

### ISSUE THREAD

**Issue by Nassim678** [udacity/ud839_Miwok#241]
please help !!
I could not find a solution for this error:
Could not initialize class com.android.sdklib.repositoryv2.AndroidSdkHandler.

**Comment by ghost** [comment]
just type in google() under the buildscript -->repositories 

like this:-

buildscript {
    repositories {
        mavenCentral()
        google()
    }

this would work for you

**Comment by ghost** [comment]
Just paste the below cod ein build.gradle

buildscript {
    repositories {
        mavenCentral()
        google()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:4.2.2'
    }

}

**Comment by SudKul** [comment]
That's right. 
`jcenter()` has been deprecated, and `mavenCentral()` is the new home for non-Google dependencies.
