### ISSUE TITLE
Cannot resolve symbol 'AppCompatActivity'

### ISSUE THREAD

**Issue by ashu305** [udacity/ud839_Miwok#242]
Can Someone help me out, please 
I have tried a lot of things but I'm not able to resolve this error.

**Comment by piyush921** [comment]
You can try File > Invalidate & Restart.
If not solved then share screenshots and codes.

**Comment by SudKul** [comment]
That's right. Sometimes, you just need to Invalidate & Restart the IDE. 
Tip: In case you face some unexpected errors with the Emulator, it will be beneficial to wipe out the AVD data by going to Tools >> Device Manager >> Select Device >> Wipe out option
