### ISSUE TITLE
 In 2021, the starter code gradle sync issue

### ISSUE THREAD

**Issue by Rohit570k** [udacity/ud839_Miwok#243]
### In 2021, the starter code gradle sync issue

The old app requires:

- Android SDK 

- Android Build Tools v23.0.2

- Android Support Repository v23.3.0

**So I install android build tools v23.0.2 but still a sync error every time**

Gradle sync started
### Error message is-

**14:34  Gradle sync failed: Unsupported method: SyncIssue.getMultiLineMessage().
          The version of Gradle you connect to does not support that method.  
         To resolve the problem you can change/upgrade the target version of Gradle you connect to.
          Alternatively, you can ignore this exception and read other information from the model.
          Consult IDE log for more details (Help | Show Log) (17 s 149 ms)**

### For solving this issue
the below changes  in the following Gradle file is needed:

`build.gradle` and `gradle-wrapper.properties`

**In the build.gradle file**,

-   just below `jcenter()`  in both the  `buildscript` and `allprojects` add this block of code

`maven {
            url 'https://maven.google.com/'
            name 'Google'
        }`

**&**
- changed the classpath to classpath 'com.android.tools.build:gradle:4.1.1'

 **In the griddle-wrappers.properties file** ,

`distributionUrl=https://services.gradle.org/distributions/gradle-2.10-all.zip`
to
`distributionUrl=https://services.gradle.org/distributions/gradle-6.5-all.zip`

**Comment by Himanshu8085** [comment]
Follow these steps: In 2021
1.Download and Extract the Zip
2.Open the folder->app->src
3.Copy this src folder
4.Make an Empty Project
3. Go to the Same path: Open the folder->app->src
4. Delete this src folder and REPLACE with the src that we copyed.
5. Go to Andriod studio and open the project.
6. DONE!

**Comment by Himanshu8085** [comment]
In Short just replace the src folder.

**Comment by SkyrunnerOO7** [comment]
Very help full thank you.

**Comment by Suvradeep1** [comment]
thank you

**Comment by ghost** [comment]
> Follow these steps: In 2021
> 1.Download and Extract the Zip
> 2.Open the folder->app->src
> 3.Copy this src folder
> 4.Make an Empty Project
> 3. Go to the Same path: Open the folder->app->src
> 4. Delete this src folder and REPLACE with the src that we copyed.
> 5. Go to Andriod studio and open the project.
> 6. DONE!

Thank you so much for this helpful advice. I literally was going crazy because of this problem until I found your solution.

**Comment by Subhajitongit** [comment]
change the android java to androidx by changing it to:

import androidx.appcompat.app.AppCompatActivity;

**Comment by Nishant0073** [comment]
If You get any error related to the AndroidMenifest.xml file the Add the following line to each activity in AndroidMenifest.xml file
`android:exported="true"`

Example:

```
  <activity android:name=".MainActivity"
            android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
       </activity>

```

**Comment by mohamed99akram** [comment]
Thank you guys

**Comment by Vishakha-Chauhan** [comment]
> Follow these steps: In 2021 1.Download and Extract the Zip 2.Open the folder->app->src 3.Copy this src folder 4.Make an Empty Project 3. Go to the Same path: Open the folder->app->src 4. Delete this src folder and REPLACE with the src that we copyed. 5. Go to Andriod studio and open the project. 6. DONE!

thank you so much  :)

**Comment by SudKul** [comment]
We have updated all branches to use Gradle 7.x, SDK API level 31, and AndroidX dependencies.
