### ISSUE TITLE
Need help!!!

### ISSUE THREAD

**Issue by NTS2k1BK** [udacity/ud839_Miwok#246]
After downloading  project by Zip file, i opened and didnot see any drawable packages in it.Anyone can help me,please!!!

**Comment by karm-patel** [comment]
> After downloading project by Zip file, i opened and didnot see any drawable packages in it.Anyone can help me,please!!!

I had the same problem, Actually, we are downloading the default branch "lesson-one" and in that branch drawable folders are not there.

Solution: We need to download files of a particular commit (commit id is given in [repo url](https://github.com/udacity/ud839_Miwok/tree/088b799406820a3a6145744168b7e6862462202a)).

Execute the following commands:
```
git clone https://github.com/udacity/ud839_Miwok.git
```
```
cd ud839_Miwok
```
```
git checkout 088b799406820a3a6145744168b7e6862462202a
``` 

Now, again check your res directory, "drawable" packages will be extracted :)

**Comment by Subrata-Rajak** [comment]
You can clone a single and particular branch also... 
Just create a new folder and open git bash or whatever editor you are using and follow the command written below

> git clone --single-branch --branch <branch name> <URL>

**Comment by Subrata-Rajak** [comment]
You can clone a single and particular branch also...
Just create a new folder and open git bash or whatever editor you are using and follow the command written below

`git clone --single-branch --branch branch_name repo_link`

**Comment by SudKul** [comment]
Thanks everyone, for to take part in this discussion. 

- We recommend you to use the [Version Control System](https://developer.android.com/studio/intro#version_control_basics)(VCS) in your Android Studio 3.2.x+ IDE to clone the repository directly in your IDE.
- You may have to use the File > Settings > Version Control (VCS) menu option to set up Git settings.
- Refer to this [IntelliJ document](https://www.jetbrains.com/help/idea/version-control-integration.html) for details.
- Working with VCS will make it easy for you to push your updates or switch between branches to your remote repository in Github.
