### ISSUE TITLE
When i run the app it gives Manifest merger failed error.

### ISSUE THREAD

**Issue by ghost** [udacity/ud839_Miwok#249]
Manifest merger failed : Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**Comment by SudKul** [comment]
That's right. This is the updated [AndroidManifest.xml file](https://github.com/udacity/ud839_Miwok/blame/4fb926454cafd42f44ba24b59c3cae7a2e271b46/app/src/main/AndroidManifest.xml#L25)
