### ISSUE TITLE
help me fast

### ISSUE THREAD

**Issue by atul-chaudhary** [udacity/ud839_Miwok#25]
![screenshot 7](https://user-images.githubusercontent.com/29684573/27513671-1dd9ac00-598d-11e7-8121-aa25e9605b12.png)

**Comment by atul-chaudhary** [comment]
Gradle sync failed: SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.
			Consult IDE log for more details (Help | Show Log)

**Comment by Kvaibhav01** [comment]
Try rebuilding and then cleaning the project. Also, update your SDKs via SDK Manager.

**Comment by vcctu85** [comment]
Closing this issue because student's question was answered.
