### ISSUE TITLE
not working xml & not showing run app

### ISSUE THREAD

**Issue by mohammed99Ali** [udacity/ud839_Miwok#250]
![image](https://user-images.githubusercontent.com/100201927/155118026-f7177a62-0297-4415-b0c9-dbd732ccc5f8.png)

**Comment by mohammed99Ali** [comment]
@SudKul do u know ?
can u help 😓

**Comment by VedantNaik21** [comment]
Same here, the gradle build sync is not being completed successfully.

**Comment by chetanpatil2703** [comment]
do is from version control
it worked for me

**Comment by BHUPENDRA28D** [comment]
Hi Chetna you can download new Miwok app from github 2021 version  it will
work fine in your android studio.

**Comment by SudKul** [comment]
@mohammed99Ali 
Were you able to find a fix? I cannot replicate the issue using the latest code available in this repo. Here are my platform/tools version:

Android Studio Bumblebee | 2021.1.1 
macOS 11.3.1
Gradle JDK v 11.x.x
AVD API level 31 / Android 12

<img width="1535" alt="Screenshot 2022-06-15 at 3 27 41 PM" src="https://user-images.githubusercontent.com/48475411/173801258-9cfe15e9-7bd1-492b-a3d1-7d7940cc8cdb.png">


We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors. 

Tip: Do not upgrade anything merely based on the IDE suggestions.
