### ISSUE TITLE
Problems with strings (need help)

### ISSUE THREAD

**Issue by JorgeRibeiroGomes** [udacity/ud839_Miwok#26]
I'm not hable to pass the miwok words and setences, it get-me errors any time i try, i tried to create the resource file called "donottranslate", i tried to pass the string values for the miwok words in the strings resources file and nothing... can someone help-me please

**Comment by vcctu85** [comment]
Hi @JorgeRibeiroGomes, I'll need more information in order to help you resolve your issue. How are you writing the code in donottranslate.xml?

**Comment by JorgeRibeiroGomes** [comment]
Resolved Thank's anyway
