### ISSUE TITLE
Can't resolve AppCompatActivity 

### ISSUE THREAD

**Issue by Daneyl** [udacity/ud839_Miwok#27]
I've imported this code into my android studio but having problem in it...
it says AppCompatActivity can't be resolved
moreover style parent setting is even a issue...
please help asap...
Thanks

**Comment by Kvaibhav01** [comment]
Hey @Daneyl, try this method:

Go to your _build.gradle_ file and in your dependencies find the _appcompat_ one, it will be something like `compile com.android.support:appcompat-v7:XX.X.X`

Change it to `compile com.android.support:appcompat-v7:XX.X.+`. Then you need to sync the project with gradle.

As for your second issue of style parent setting, I want you to be more clear by giving some code example.

**Comment by kvarinder007** [comment]
in style.xml change 

-    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
to
+    <style name="AppTheme" parent="Base.Theme.AppCompat.Light.DarkActionBar">


review this change too
(https://github.com/udacity/ud839_Miwok/pull/29/commits/3dc77f15c5daffa7597fc7bd5a51d8f9b6251ffd)

**Comment by pvnakum** [comment]
please try this solution

https://stackoverflow.com/questions/34947794/cant-resolve-appcompatactivity/50897316#50897316

**Comment by tapansingh10a** [comment]
hi, @Daneyl 
Go to your build.gradle file and in your dependencies find the appcompat one, it will be something like 

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation 'com.android.support:appcompat-v7:23.3.0'
    implementation 'com.android.support:support-v4:23.3.0'
    implementation 'com.android.support:design:23.3.0'
}

change them into

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation 'com.android.support:appcompat-v7:23.4.0'
    implementation 'com.android.support:support-v4:23.4.0'
    implementation 'com.android.support:design:23.4.0'
}

**Comment by Adithyaj467** [comment]
step 1. go to build
step 2.select edit libraries and dependencies 
step 3. click (+) icon to add and type com.android.support:design:23.4.0 
step 4. sync  gradle

**Comment by JediMaster-Ai** [comment]
The issue could be import reference, try changing it.
From:
`import android.support.v7.app.AppCompatActivity;`

To:
`import androidx.appcompat.app.AppCompatActivity;`

**Comment by Blankedmaker** [comment]
Hi.


Check out my solution here:


https://github.com/udacity/ud839_Miwok/issues/168

**Comment by i-am-alien** [comment]
**import androidx.appcompat.app.AppCompatActivity;**

just import this file and delete this**(import android.support.v7.app.AppCompatActivity;)**

**Comment by dianavintila** [comment]
https://stackoverflow.com/questions/57655435/what-replaced-appcompat-v7-in-androidx
just import import androidx.appcompat.app.AppCompatActivity :)

**Comment by shivani-jariwala** [comment]
![image](https://user-images.githubusercontent.com/64823330/82354395-60166c00-9a1e-11ea-95d8-d193d694bb1f.png)
please help me to solve this error

**Comment by f4ni** [comment]
Just Downgrade gradle version to 3.6.1, and voila, errors removed.
