### ISSUE TITLE
SetOnClickListener issue

### ISSUE THREAD

**Issue by mnjayaram** [udacity/ud839_Miwok#3]
In the MainActivity.java file the all occurrences of new OnClickListener() should be new View.OnClickListener()

**Comment by Sinapse87** [comment]
Hi @mnjayaram the "new OnClickListener()" is implicitly calling View.OnClickListener() as per import. No need to specify that . Let me know if you agree.

**Comment by Sinapse87** [comment]
Issue should be closed

**Comment by ghost** [comment]
![1](https://cloud.githubusercontent.com/assets/17499827/21859616/588902da-d853-11e6-9dd9-054275a236a9.PNG)
it is saying "cannot resolve setOnClickListener" what to do

**Comment by diwesh87** [comment]
Sometimes this happens when you simply copy paste the code and the compiler fails to recognize. Try Build -> Clean and see if it helps. This cleans your code and rebuilds everything for you, so some temporary errors just go away.

**Comment by ghost** [comment]
Thank you.. It works!

**Comment by sanyukta123** [comment]
Hi @InvinsibleMe.. Paste your code inside the OnCreate method as shown below:

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        //Set the content of the activity to use the activity_main.xml layout file
        setContentView(R.layout.activity_main);

        //Find the View that show the numbers category
        TextView numbers = (TextView)findViewById(R.id.numbers);
        //Set a clickListener on that View
        numbers.setOnClickListener(new View.OnClickListener(){
            @Override
            public void onClick(View view){
                //Create a new intent to open the {@link Number Activity}
                Intent numbersIntent = new Intent(MainActivity.this, NumbersActivity.class);

                //Start the new Activity
                startActivity(numbersIntent);
            }
        });
       ....


 The red lines as you show in your code should go. Hope it helps you. You can close the issue.

**Comment by vcctu85** [comment]
Closing this issue because question is answered.

**Comment by AlanTso** [comment]
I try all of the above and still face the same problem.
