### ISSUE TITLE
cannot resolved NumbersActivity 

### ISSUE THREAD

**Issue by iarunsingh07** [udacity/ud839_Miwok#30]
![screenshot 60](https://user-images.githubusercontent.com/30037827/28489687-d7682aee-6ee5-11e7-9d79-810064beb405.png)

**Comment by Kvaibhav01** [comment]
I think you made spelling mistake there. It's [NumbersActivity](https://github.com/udacity/ud839_Miwok/blob/lesson-one/app/src/main/java/com/example/android/miwok/NumbersActivity.java) not NumberActivity.

**Comment by iarunsingh07** [comment]
Brother i tried with every other alternatives

**Comment by Kvaibhav01** [comment]
Can you share the error log in Android Studio? That will help.
