### ISSUE TITLE
gradle sync failed

### ISSUE THREAD

**Issue by pratsk95** [udacity/ud839_Miwok#31]
I am getting this error..please help me..i had given the right path of SDK still the error occurs.
`
 SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.example.android.miwok"
        minSdkVersion 15
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.android.support:support-v4:23.3.0'
    compile 'com.android.support:design:23.3.0'
}
`

**Comment by Kvaibhav01** [comment]
Close the current project and you'll see pop up with dialog which will then proceed to _Configure_ option.

Then go to Configure -> Project Defaults -> Project Structure -> SDKs on left column -> Android SDK Home Path -> give the exact path as you did on local.properties and select _Valid Target_.
