### ISSUE TITLE
cannot import the zip file

### ISSUE THREAD

**Issue by AjayJohnAlex** [udacity/ud839_Miwok#32]
i have tried importing the downloaded zip file....but its not working...what should i do now ??

**Comment by Kvaibhav01** [comment]
What do you mean by _not working_? Check if Android Studio is prompting any error(s) and try to provide its screenshot/error log here.

You may need to update _build.gradle_ file to the or go to File -> Invalidate Caches/Restart.

**Comment by AjayJohnAlex** [comment]
Updated build.gradle file and its working fine .
