### ISSUE TITLE
can't import project 

### ISSUE THREAD

**Issue by adelascasas** [udacity/ud839_Miwok#34]
For some reason everytime I download the zip file and try to open it up in android studio I get 
"Cannot import anything from C:/Users/Anghel/Downloads/ud839_Miwok-Starter-code.zip"

**Comment by Kvaibhav01** [comment]
Check these:-

1. Go to File > Invalidate Caches/Restart. _OR_
2. Are you sure your IDE is good at locating your Android SDK? (https://stackoverflow.com/questions/16581752/android-studio-how-to-change-android-sdk-path/18409923#18409923) _OR_
3. Clean and Rebuild the project.

**Comment by adelascasas** [comment]
Thanks for the help. I seem to have imported the project but it only contains the java classes and nothing else. Is there a way to access the xml and other resources?

**Comment by Kvaibhav01** [comment]
How is that possible? Are you sure you downloaded this project correctly? It should contain all the assets and files. Surely, you can see the XML file(s) by going into the directory of the project under _Project Name > app > src > main > res folder_.

**Comment by Mohamed2del** [comment]
I have the same problem but when I import the file it takes forever, so I searched for solution on internet I found out I can delete some files from this Gradle things so its opens with errors what should I do now ?? 
iam stuck for 2 days now

**Comment by adelascasas** [comment]
I actually downloaded it incorrectly and that fixed it. Did you download it correctly?

**Comment by Kvaibhav01** [comment]
Yup, I did!

**Comment by KarMurri** [comment]
You need to unzip the file, you're oppening the .zip file.
