### ISSUE TITLE
No XML and gradle not running

### ISSUE THREAD

**Issue by EdwardPJ** [udacity/ud839_Miwok#39]
I have spent 2 hours trying to fix this and I'm at a complete loss as to what to do...
I have updated Android Studio and it still doesn't work.

I unzip the zipped folder. I import a project. I select the imported project.

The next bit frustrates me because there are a tonne of options and stages to go through and no where is there any indication of how to navigate this. Most of the terminology is completely new to me but it is assumed I should understand it.

Anyway,I import from a file (rather than externally). I then leave it at 1.8SDK although I also attempted the other options.

When the project loads up it says it isn't running gradle and all internet instructions on how to address this, including the Android page do not seem to be having this issue. 
There is also no xml visible, only java
The java also has many errors
There is also no way of running the app

Please help me get past these issues?!!!
Thank you
Ed

**Comment by EdwardPJ** [comment]
Just to add the above, this is the process I go through once I've started the import procedure:
'Create project from existing sources'
Then I leave everything ticked as it suggests
Then I select 1.8SDK
Then when the project loads up it says at the bottom "This project does not use the Gradle build system. We recommend that you migrate to the Gradle build system."
It then provides a link which goes on about Eclipse and Intellij

What am I supposed to do?

**Comment by Kvaibhav01** [comment]
You need to [reconfigure Android Studio](https://stackoverflow.com/a/35219457) or reinstall it. Plus, import this project as:-

1. [Downloading](https://github.com/udacity/ud839_Miwok/archive/lesson-one.zip) the project. 
2. Locating and opening the reinstalled/reconfigured IDE and clicking on the Open Project button or File > Open Project.
Let Gradle sync the project. First time it may take a while. 

Also if you still run into an issue try adding a screenshot of the logcat or the errors shown in your next comment. Or you can ask on [StackOverflow](https://stackoverflow.com/).
