### ISSUE TITLE
A different approach 

### ISSUE THREAD

**Issue by pramodsravan** [udacity/ud839_Miwok#42]
I just tried to use the WordAdapter alone to also pick up audio resources for the currentWord as well as managing AudioFocus. This way I never really needed to modify all the category activities (NumbersActivity, FamilyActivity, etc…).

This is what it looks like:

`package com.example.android.miwok;

import android.app.Activity;
import android.content.Context;
import android.media.AudioManager;
import android.media.MediaPlayer;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.v4.content.ContextCompat;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;
import android.widget.ImageView;
import android.widget.TextView;

import java.util.ArrayList;

/**
 * Created by @pramdsravan on 8/11/2017.
 */

public class WordAdapter extends ArrayAdapter<Word> {
    private static final String LOG_TAG = WordAdapter.class.getSimpleName();
    private static MediaPlayer mediaPlayer;
    private int mColorResourceId;
    private AudioManager mAudioManager;
    //Register an onAudioFocusChangeListener
    AudioManager.OnAudioFocusChangeListener mOnAudioFocusChangeListener = new AudioManager.OnAudioFocusChangeListener() {
        @Override
        public void onAudioFocusChange(int focusChange) {
            // || = "or"
            if (focusChange == AudioManager.AUDIOFOCUS_LOSS_TRANSIENT ||
                    focusChange == AudioManager.AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK) {
                    /* The AUDIOFOCUS_LOSS_TRANSIENT case means we've lost audio focus for a
                    * short amount of time. The AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK case means
                    * our app is allowed to continue playing sound but at a lower volume. We want
                    * both cases the same way because our app is playing short sound files.*/
                // Pause playback and reset player.
                mediaPlayer.pause();
                // To restart the audiofile from the beginning, instead of resume playback
                mediaPlayer.seekTo(0);

                // Pause playback
            } else if (focusChange == AudioManager.AUDIOFOCUS_GAIN) {
                // The AUDIOFOCUS_GAIN case means we have regained focus and can resume playback
                mediaPlayer.start();
            } else if (focusChange == AudioManager.AUDIOFOCUS_LOSS) {
                // AUDIOFOCUS_LOSS means we've lost audiofocus & should stop playback and
                // clean up resources
                releaseMediaPlayer();
            }
        }
    };

    /**
     * This is our own custom constructor (it doesn't mirror a supercalss constructor).
     * The context is used to inflate the layout file, and the list is the data we want to populate into the lists.
     *
     * @param context The current context. Used to inflate the layout file.
     * @param words   A list of default & Miwok words to diplay in a list.
     */

    public WordAdapter(Activity context, ArrayList<Word> words, int colorResourceId) {
        //Here, we initialize the ArrayAdapter's internal storage for the context and the list.
        //The second argument is used when the ArrayAdapter is populating a single TextView.
        //Because this is a custom adapter for two TextViews and an Image VIew, the adapter is not
        //going to use this second argument, so it can be any value. Here, we used 0.
        super(context, 0, words);
        mColorResourceId = colorResourceId;
    }

    /**
     * Provides a view for an AdapterView (ListView, GridView, etc.)
     *
     * @param position    The position in the list of data that should be displayed in the list item view.
     * @param convertView The recycled view to populate.
     * @param parent      The parent ViewGroup that is used for inflation.
     * @return The View for the position in the AdapterView.
     */
    @NonNull
    @Override
    public View getView(int position, @Nullable View convertView, @NonNull ViewGroup parent) {
        //Check if the existing view is being reused, otherwise inflate the view
        View listItemView = convertView;
        if (listItemView == null) {
            listItemView = LayoutInflater.from(getContext()).inflate(R.layout.list_item, parent, false);
        }
        //Get the {@link Word} object loacted at this position in the list
        final Word currentWord = getItem(position);

        //Find the TextView in the list_item.xml layout with the Id item_2
        TextView defaultTextView = (TextView) listItemView.findViewById(R.id.item_2);
        //Get the default translation of the current default Word object and set this text on the miwok TextView
        defaultTextView.setText(currentWord.getDefaultTranslation());

        //Find the TextView in the list_item.xml layout with the Id item_1
        TextView miwokTextView = (TextView) listItemView.findViewById(R.id.item_1);
        //Get the miwok translation of the current Word object and set this on miwok TextView
        miwokTextView.setText(currentWord.getMiwokTranslation());

        //Find the ImageView in the list_item.xml layout with the Id image_1
        ImageView imageView = (ImageView) listItemView.findViewById(R.id.image_1);
        // Check if an Image is provided for the currentWord
        if (currentWord.hasImage()) {
            //Get the imageResource of the currnet Word object and set this on imageView
            imageView.setImageResource(currentWord.getImageResourceId());
            //Make sure the view is visible
            imageView.setVisibility(View.VISIBLE);
        } else {
            //Otherwise hide the imageView
            imageView.setVisibility(View.GONE);
        }

        //set the background color for the text container
        View textContainer = listItemView.findViewById(R.id.text_container);
        int color = ContextCompat.getColor(getContext(), mColorResourceId);
        textContainer.setBackgroundColor(color);

        //set onClickListener on the textContainer to trigger audio playback
        textContainer.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                if (requestAF() == AudioManager.AUDIOFOCUS_REQUEST_GRANTED) {
                    //release mediaPlayer if it is already invoked
                    releaseMediaPlayer();
                    //set up the mediaPlayer to playback miwok words
                    mediaPlayer = MediaPlayer.create(getContext(), currentWord.getAudioResourceId());
                    //play audio file
                    mediaPlayer.start();
                    //release mediaPlayer resource once the audio completes
                    mediaPlayer.setOnCompletionListener(new MediaPlayer.OnCompletionListener() {
                        @Override
                        public void onCompletion(MediaPlayer mediaPlayer) {
                            releaseMediaPlayer();
                            mAudioManager.abandonAudioFocus(mOnAudioFocusChangeListener);
                        }
                    });
                }
            }
        });
        return listItemView;
    }

    //Helper method to release MediaPlayer resources
    public static void releaseMediaPlayer() {
        //if mediaPlayer is not null, it may be currently playing a sound
        if (mediaPlayer != null) {
            //Irrespective of mediaPlayer state, release its reources becasue we no longer need it
            mediaPlayer.release();
            //setting mediaPlayer to null to indicate it is idle.
            mediaPlayer = null;
        }
    }

    //Manage AudioFocus
    public int requestAF() {
        mAudioManager = (AudioManager) getContext().getSystemService(Context.AUDIO_SERVICE);
        int result = mAudioManager.requestAudioFocus(mOnAudioFocusChangeListener, AudioManager.STREAM_MUSIC, AudioManager.AUDIOFOCUS_GAIN_TRANSIENT);
        return result;
    }
}`

And here's what my NumbersActivty looks like.
All my other activities look pretty much the same.

`package com.example.android.miwok;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.widget.ListView;

import java.util.ArrayList;

public class NumbersActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.word_list);

        //Create list of words
        ArrayList<Word> words = new ArrayList<Word>();

        /*Collections.addAll(words, "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten");
        LinearLayout rootView = (LinearLayout) findViewById(R.id.rootView);
        int index = 0;
        while (index < words.size()) {
            TextView wordView = new TextView(this);
            wordView.setText(words.get(index));
            rootView.addView(wordView);
            index++;
        }*/

        words.add(new Word("one", "lutti", R.drawable.number_one, R.raw.number_one));
        words.add(new Word("two", "otiiko", R.drawable.number_two, R.raw.number_two));
        words.add(new Word("three", "tolookosu", R.drawable.number_three, R.raw.number_three));
        words.add(new Word("four", "oyyisa", R.drawable.number_four, R.raw.number_four));
        words.add(new Word("five", "massokka", R.drawable.number_five, R.raw.number_five));
        words.add(new Word("six", "temmokka", R.drawable.number_six, R.raw.number_six));
        words.add(new Word("seven", "kenekaku", R.drawable.number_seven, R.raw.number_seven));
        words.add(new Word("eight", "kawinta", R.drawable.number_eight, R.raw.number_eight));
        words.add(new Word("nine", "wo’e",R.drawable.number_nine, R.raw.number_nine));
        words.add(new Word("ten", "na’aacha",R.drawable.number_ten, R.raw.number_ten));

        /*ArrayAdapter<String> itemsAdapter = new ArrayAdapter<String>(this, android.R.layout.simple_list_item_1, words);
        ListView listView = (ListView) findViewById(R.id.list);
        listView.setAdapter(itemsAdapter);*/
        //GridView gridView = (GridView) findViewById(R.id.list);
        //gridView.setAdapter(itemsAdapter);

        //Cretae an {@link WordAdapter}, whoise data source is a list of {!link Word}s.
        //The adapter knows how to create list items for each item in the list.

        WordAdapter adapter = new WordAdapter(this, words, R.color.category_numbers);

        // Find the {@link ListView} object in the view hierarchy of the {@link Activity}.
        // There should be a {@link ListView} with the view ID called list, which is declared in the
        // word_listyout file.

        ListView listView = (ListView) findViewById(R.id.list);

        // Make the {@link ListView} use the {@link WordAdapter} we created above, so that the
        // {@link ListView} will display list items for each {@link Word} in the list.

        listView.setAdapter(adapter);
    }

    @Override
    protected void onStop(){
        super.onStop();
        WordAdapter.releaseMediaPlayer();
    }
}`

**Comment by pramodsravan** [comment]
The only issue I observe is that the app crashes occasionally and it is totally random. There is no pattern.
This is the message from Logcat:
Any Ideas whats going on?

FATAL EXCEPTION: main
                                                                         Process: com.example.android.miwok, PID: 7388
                                                                         java.lang.NullPointerException
                                                                             at com.example.android.miwok.WordAdapter$1.onAudioFocusChange(WordAdapter.java:47)
                                                                             at android.media.AudioManager$FocusEventHandlerDelegate$1.handleMessage(AudioManager.java:2908)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:146)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5692)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:515)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                                             at dalvik.system.NativeStart.main(Native Method)

**Comment by Kvaibhav01** [comment]
These are a ton of errors. Try formatting your code an specifying only the changed lines. It's too hard to read the whole code. Also, for your logcat errors try _alt+enter_ at the error line and see what Android Studio tells you.

**Comment by pramodsravan** [comment]
So basically, I have set the onAudioFocusChangeListener in the WordAdapter class itself instead of setting it up in every activity class.
Everything is working as expected except for these occasional crashes.
I tried to hit alt+enter on those errors in the logcat, nothing happened though.
