### ISSUE TITLE
Can not open the project

### ISSUE THREAD

**Issue by HessaAlrasheed** [udacity/ud839_Miwok#43]
I tried many ways to open the project, but none of them works with me. I stuck in "Building 'Miwok' Gradle project info! I been looking for many solution online for this is problem but none of them solve my problem. Pleas help me!

**Comment by Kvaibhav01** [comment]
Hey @HessaAlrasheed! Try cleaning up and then rebuilding up the project. You'll find this in _Build > Clean solution_ and _Build > Build solution_. Else, you may need to check that all of the required SDK components are installed properly. Finally, try to give us the logcat/error report (if any) in your next comment.
