### ISSUE TITLE
Shouldn't {@link ...} tag be used inside a JavaDoc comment?

### ISSUE THREAD

**Issue by Phoenix-Brothres** [udacity/ud839_Miwok#5]
I saw these tags inside  regular comments [here](https://github.com/udacity/ud839_Miwok/blob/3b03dc9d978c7c412c907d23d4c4f4aba10d6d8f/app/src/main/java/com/example/android/miwok/NumbersActivity.java), Shouldn't those tag be inside a JavaDoc comment to work? Something like the following format for example.

```
/**
* {@link android.widget.ArrayAdapter}
*/
```

**Comment by Kvaibhav01** [comment]
Hey @Phoenix-Brothres, the `android.widget.ArrayAdapter;` is an `import ` statement which should be used to import the `ArrayAdapter ` class. You cannot use [this ](https://github.com/udacity/ud839_Miwok/blob/3b03dc9d978c7c412c907d23d4c4f4aba10d6d8f/app/src/main/java/com/example/android/miwok/NumbersActivity.java#L20) statement inside a tag! 

You use `javadoc` to parse the declarations and documentation comments in a set of Java source files. [See more](http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javadoc.html).
