### ISSUE TITLE
I use the MediaPlayer class in WordAdapter

### ISSUE THREAD

**Issue by diegosawa** [udacity/ud839_Miwok#50]
`        //Set the audio from the resource ID

        final MediaPlayer mediaPlayer = MediaPlayer.create(getContext(), currentWord.getAudioResourceId());

        textContainer.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                mediaPlayer.start();// no need to call prepare(); create() does that for you

            }
        });

        // Return the whole list item layout (containing 2 TextViews) so that it can be shown in
        // the ListView.
        return listItemView;
    }
}`

**Comment by SudKul** [comment]
Submit a PR if you want to suggest any improvements.
