### ISSUE TITLE
Gradle Sync Error . 

### ISSUE THREAD

**Issue by RabbiHasanR** [udacity/ud839_Miwok#51]
Error:Failed to open zip file.
```
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)
Re-download dependencies and sync project (requires network)
```

**Comment by Kvaibhav01** [comment]
Hey @Rabbi50! Checkout the following:

1. Make sure that you're not importing the .zip file of this project. You need to first extract it and then open it.
2. If you get the error, _Gradle's dependency cache may be corrupt_ then you need to update Android Studio to the latest build configuration. Just update the Gradle plugin and build tools to solve the error.

❗️ Make sure that you sync the project after each step!

**Comment by maiossaid** [comment]
I did that but i still have that error !

**Comment by Kvaibhav01** [comment]
> Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
> Re-download dependencies and sync project (requires network)
> Re-download dependencies and sync project (requires network)

All of this means that your device is experiencing network related issues. Either the network strength is poor or the downloading speed is slow. Try to fix your network connections.

**Comment by prateekj117** [comment]
@Rabbi50 @maiossaid Follow this. https://www.youtube.com/watch?v=ZV2HFw8KY9U&t=11s
