### ISSUE TITLE
Failed to load AppCompat ActionBar with unknown error.

### ISSUE THREAD

**Issue by YasserMagdad** [udacity/ud839_Miwok#54]
hi, when imported the app. the preview window doesn't work with the error message below of it.
''Failed to load AppCompat ActionBar with unknown error.''

**Comment by Kvaibhav01** [comment]
Use:

```
compile 'com.android.support:appcompat-v7:26.0.0'
```


with:

```
buildToolsVersion '26.0.0' 
```


and

```
classpath 'com.android.tools.build:gradle:3.0.0-alpha8

```
In your Gradle.

**Comment by YasserMagdad** [comment]
I still get an error message :(
 Error:Error:line (25)Could not find method classpath() for arguments [com.android.tools.build:gradle:3.0.0-alpha8] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

apply plugin: 'com.android.application'

    android {
        compileSdkVersion 26
        buildToolsVersion '26.0.2'

    defaultConfig {
        applicationId "com.example.android.miwok"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
    }


    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0-alpha8'
        compile fileTree(dir: 'libs', include: ['*.jar'])
        testCompile 'junit:junit:4.12'
        compile 'com.android.support:design:26.0.2'
        compile 'com.android.support:appcompat-v7:26.0.2'

    }

**Comment by Kvaibhav01** [comment]
Try to _clean and rebuild the project_ using previous Gradle scripts. Also checkout [this answer](https://stackoverflow.com/a/44071571) for reference.

**Comment by JaxCastonguay** [comment]
same error. change your gradle to look like this then rebuild and clean.
code:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion '26.0.2'

    defaultConfig {
        applicationId "com.example.android.miwok"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.android.support:support-v4:26.+'
    compile 'com.android.support:design:26.+'
}

**Comment by deniskasyanov** [comment]
I had similar problem (maybe not exactly the same one).

I was able to run the starter code on the phone and the menu was there. However, preview pane in Android Studio didn't show actual layout.  Instead it showed `android...ActionBarOverlayLayout`. 

I have fixed it by changing `Theme.AppCompat.Light.DarkActionBar` to `Base.Theme.AppCompat.Light.DarkActionBar` in `styles.xml`.

Link to original solution - https://stackoverflow.com/questions/44223687/render-error-in-android-studio-3-0-layout-editor/45002903#45002903

**Comment by kindeep** [comment]
deniskasyanov's solution worked! not sure why, but it did.

**Comment by kindeep** [comment]
encountered another issue, if i change colorPrimaryDark in styles.xml, it does not show up in the preview, but it does show up in the app. Been having issues after the update.

**Comment by Kvaibhav01** [comment]
@kargq, try to change the theme from `Theme.AppCompat.Light.DarkActionBar` to `Base.Theme.AppCompat.Light.DarkActionBar` in `styles.xml`.

**Comment by hernanlaborde** [comment]
@Kvaibhav01   The last solution works fine :
"change the theme from Theme.AppCompat.Light.DarkActionBar to base.Theme.AppCompat.Light.DarkActionBar in styles.xml."      thanks.

**Comment by codeashish247** [comment]
Sync the gradle with earlier version of sdk as the current version is full of bugs. Do the following changes. It  should work. 

app gradle should like this:

apply plugin: 'com.android.application'


android {
    buildToolsVersion '27.0.3'
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.example.ashish.tapca"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'



}

apply plugin: 'com.google.gms.google-services'

Add classpath dependencies:
  classpath 'com.android.tools.build:gradle:3.3.0-alpha02'

**Comment by realDuYuanChao** [comment]
I fix this error using 3 methods on YouTube

[![Solution](https://img.youtube.com/vi/IlsuFTnkHAI/0.jpg)](https://www.youtube.com/watch?v=IlsuFTnkHAI)

**Comment by darkmatter18** [comment]
I have faced the same problem. After searching on the Web, I found that the problem is actually is on the SDK.
So, as a solution, I opened the **SDK manager**, and found that **Android API 28** SDK is installed, which is actually not stable.
So, I simply, 
1- Uninstall the **API 28 SDK**
2- Install the **Oreo 8.1 27 SDK**
3- Open my project
4- Wait for Sync and Build Gradle

And It's working perfectly now

**Comment by darkmatter18** [comment]
I have faced the same problem. After searching on the Web, I found that the problem is actually is on the SDK.
So, as a solution, I opened the **SDK manager**, and found that **Android API 28** SDK is installed, which is actually not stable.
So, I simply, 
1- Uninstall the **API 28 SDK**
2- Install the **Oreo 8.1 27 SDK**
3- Open my project
4- Wait for Sync and Build Gradle

And It's working perfectly now

**Comment by alarimer** [comment]
Perhaps the "Build Your First App" tutorial should be updated!

**Comment by Faizzy** [comment]
> @kargq, try to change the theme from `Theme.AppCompat.Light.DarkActionBar` to `Base.Theme.AppCompat.Light.DarkActionBar` in `styles.xml`.

Its works fine.Thanks for that

**Comment by NandanPandey22** [comment]
> same error. change your gradle to look like this then rebuild and clean.
> code:
> 
> apply plugin: 'com.android.application'
> 
> android {
> compileSdkVersion 26
> buildToolsVersion '26.0.2'
> 
> ```
> defaultConfig {
>     applicationId "com.example.android.miwok"
>     minSdkVersion 15
>     targetSdkVersion 26
>     versionCode 1
>     versionName "1.0"
> }
> buildTypes {
>     release {
>         minifyEnabled false
>         proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>     }
> }
> ```
> }
> 
> dependencies {
> compile fileTree(dir: 'libs', include: ['*.jar'])
> testCompile 'junit:junit:4.12'
> compile 'com.android.support:appcompat-v7:26.+'
> compile 'com.android.support:support-v4:26.+'
> compile 'com.android.support:design:26.+'
> }

Solved my problem .... Everyone try this solution
