### ISSUE TITLE
Error:Execution failed for task ':app:processDebugManifest'.

### ISSUE THREAD

**Issue by YasserMagdad** [udacity/ud839_Miwok#55]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 1 cannot be smaller than version 14 declared in library [com.android.support:design:26.1.0] C:\Users\YasserMagdad\.gradle\caches\transforms-1\files-1.1\design-26.1.0.aar\4e8ddd06535b838073632601926eff5b\AndroidManifest.xml as the library might be using APIs not available in 1
  	Suggestion: use a compatible library with a minSdk of at most 1,
  		or increase this project's minSdk version to at least 14,
  		or use tools:overrideLibrary="android.support.design" to force usage (may lead to runtime failures)

**Comment by Kvaibhav01** [comment]
Make sure you have `uses-sdk` tag in the _AndroidManifest.xml_ like:
`<uses-sdk android:minSdkVersion="14" android:targetSdkVersion="16" />`

Also you must have `minSdkVersion `and `targetSdkVersion `in the _build.gradle_ file like:
```
android {
    compileSdkVersion 17
    buildToolsVersion "17.0.0"

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 16
    }
}
```
Then rebuild and clean the project.

**Comment by ghost** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than versdiates\manifests\full\debug\AndroidManifest.xml as the library might be using AP
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 19,
                or use tools:overrideLibrary="org.apache.cordova" to force usage

**Comment by ghost** [comment]
Can anyone help me, I am getting Error like this: An Error occurred while running subprocess Cordova, I have tried all possibilities.

**Comment by Kvaibhav01** [comment]
@Sangamesh30, for your first error, the solution is in your comment only!

- use a compatible library with a minSdk of at most 16,
- or increase this project's minSdk version to at least 19,
- or use tools:overrideLibrary="org.apache.cordova" to force usage

Try these. Check [this answer](https://stackoverflow.com/a/17614937) in Stackoverflow.

For the second error, I don't think it's related to Android Studio or its framework. You can search for the same on Stackoverflow.

**Comment by SudKul** [comment]
Thanks, @Kvaibhav01 
You've resolved almost all issues posted in this repo.
