### ISSUE TITLE
Gradle, sync, opening zip errors

### ISSUE THREAD

**Issue by bhuvanaimad** [udacity/ud839_Miwok#57]
I tried all of the possible solutions but none worked. Everytime a  new error pops up 
This is the error it shows in the log now. Please help how to fix this.. have been stuck with this for almost 3 weeks now. Eagerly waiting for the MIWOK project to show up properly.

Error:Failed to open zip file.
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a>
<a href="syncProject">Re-download dependencies and sync project (requires network)</a>

**Comment by Kvaibhav01** [comment]
Prerequisites-

1. You have a stable internet connection.
2. You're not opening the downloaded ZIP file in Android Studio. Instead first extract the ZIP and then open the extracted folder in the IDE.
3. To clean and rebuild the project.
4. You have all the necessary SDK files installed. Reinstall/Update if you face issues. 

If the error still persists, then follow [this Stackoverflow answer](https://stackoverflow.com/a/42654435).

**Comment by SudKul** [comment]
Use these steps:

How to use this repository?
--------------
- Fork this repository to your Github account.
- Open Android Studio 3.2.x+ in your local machine.
- We recommend you to use the [Version Control System](https://developer.android.com/studio/intro#version_control_basics)(VCS) in your Android Studio 3.2.x+ IDE to clone the repository directly in your IDE.
- You may have to use the File > Settings > Version Control (VCS) menu option to set up Git settings.
- Refer to this [IntelliJ document](https://www.jetbrains.com/help/idea/version-control-integration.html) for details.
- Working with VCS will make it easy for you to push your updates or switch between branches to your remote repository in Github.
