### ISSUE TITLE
Tabs not showing on running the app

### ISSUE THREAD

**Issue by ShantanuShinde** [udacity/ud839_Miwok#58]
I completed the app with the same way as the code given, but the tabs re not being shown. no error is there. but when i downloaded the code and ran that, tabs are show. pls tell where i m wrong

**Comment by ShantanuShinde** [comment]
`
[miwok.zip](https://github.com/udacity/ud839_Miwok/files/1557673/miwok.zip)
[res.zip](https://github.com/udacity/ud839_Miwok/files/1557675/res.zip)
this is my code
`

**Comment by Kvaibhav01** [comment]
Check the logcat. There must a warning or an error. Or try to run the app on an different device.

**Comment by Imbernix** [comment]
Hi, you seem to be missing an adapter, setter methods an xml list item. (In case i used different variables make sure to change them)
Please let me know if this helped and/or if you need more help!

Here is the adapter
`//Adapter to fill the tabs
public class NumbersAdapter extends ArrayAdapter<Numbers> {
    //used to change color depending on the specific activity
    private int mColor;

    public NumbersAdapter(Activity context, ArrayList<Numbers> oNumbers, int colorResource){

        super(context, 0, oNumbers);
        mColor = colorResource;
    }

//Fills views in the listItemView
    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        View listItemView = convertView;
        if(listItemView == null){
            listItemView = LayoutInflater.from(getContext()).inflate(R.layout.list_item, parent, false);
        }

        Numbers currentOrdNummer = getItem(position);

        TextView miwokTextView = (TextView) listItemView.findViewById(R.id.nr1);
        miwokTextView.setText(currentOrdNummer.getmMiwokTranslation());

        TextView defaultTextView = (TextView) listItemView.findViewById(R.id.nr2);
        defaultTextView.setText(currentOrdNummer.getmDefaultTranslation());

//if there is an image in the dataset, display it in imageview otherwise
//hide imageview
        ImageView iconView = (ImageView) listItemView.findViewById(R.id.nr3);
        if (currentOrdNummer.hasImage()) {
            iconView.setImageResource(currentOrdNummer.getmImg());
            iconView.setVisibility(View.VISIBLE);
        }
        else{
            iconView.setVisibility(View.GONE);
        }

        View textContainer = listItemView.findViewById(R.id.text_container);

        int color = ContextCompat.getColor(getContext(), mColor);

        textContainer.setBackgroundColor(color);

        return listItemView;
    }
}

`
Here is the class for the setter methods
`
public class Numbers {

    private String mDefaultTranslation;
    private String mMiwokTranslation;
   
 //If there isn't any images provided
    private int mImg = NO_IMAGE_PROVIDED;
    private static final int NO_IMAGE_PROVIDED = -1;


    public Numbers(String vDefaultTranslation, String vMiwokTranslation, int imgRes) {
        this.mDefaultTranslation = vDefaultTranslation;
        this.mMiwokTranslation = vMiwokTranslation;
        this.mImg = imgRes;
    }

    public Numbers(String vDefaultTranslation, String vMiwokTranslation) {
        this.mDefaultTranslation = vDefaultTranslation;
        this.mMiwokTranslation = vMiwokTranslation;

    }

 //Setter methods for the adapter
    public String getmDefaultTranslation() {
        return mDefaultTranslation;
    }
    public String getmMiwokTranslation() {
        return mMiwokTranslation;
    }
    public int getmImg() {return mImg;}

    public boolean hasImage() {
        return mImg != NO_IMAGE_PROVIDED;
    }
}
`
and last here is the list item used to fill the tabs
`
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:background="@color/tan_background"
    android:minHeight="@dimen/list_item_height">


    
    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:orientation="horizontal">

        <ImageView
            android:id="@+id/nr3"
            android:layout_width="@dimen/list_item_height"
            android:layout_height="@dimen/list_item_height"
            android:background="#FFF7DA"

            />

        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:orientation="vertical"
            android:layout_marginLeft="16dp"
            android:id="@+id/text_container"

            >

            <TextView
                android:id="@+id/nr1"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                tools:text="One"
                android:textAppearance="?android:textAppearanceMedium"
                android:textStyle="bold"
                android:gravity="bottom"
                android:layout_weight="1"
                android:textColor="#FFFFFF"/>

            <TextView
                android:id="@+id/nr2"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="1"
                tools:text="Lutti"
                android:gravity="top"
                android:textColor="#FFFFFF"
                android:textAppearance="?android:textAppearanceMedium"
                />
        </LinearLayout>

    </LinearLayout>
</LinearLayout>
`

**Comment by 17sushmita** [comment]
In list_item.xml, set padding of rootView i.e, LinearLayout to 16dp.

> 

<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android" android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:padding="16dp"
    >
Worked for me!!
