### ISSUE TITLE
i am getting only android actionbar overlaylayout in preview

### ISSUE THREAD

**Issue by shugo111** [udacity/ud839_Miwok#61]
can anyone help me out with this ...i am not able t see the preview
i am getting only android actionbar overlaylayout
![screenshot 24](https://user-images.githubusercontent.com/34954190/34451431-6a3cd048-ed4b-11e7-8790-624297f0e9b9.png)
![screenshot 25](https://user-images.githubusercontent.com/34954190/34451432-6a7adfc8-ed4b-11e7-887f-c1d03ffda5cb.png)

**Comment by Kvaibhav01** [comment]
Looks like a Gradle issue. As far as I can see that message that you're getting in the Messages tab, you can update the build.gradle tools in your project-level build.gradle file from:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0' //THIS LINE

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```
To something like this:

`classpath 'com.android.tools.build:gradle:2.2.3'`

**Comment by since85stas** [comment]
I have the same problem, try to do what are you advicing, but it doesn't help.

**Comment by Kvaibhav01** [comment]
@since85stas try to clean and rebuild the project. OR
change the theme from `Theme.AppCompat.Light.DarkActionBar` to `Base.Theme.AppCompat.Light.DarkActionBar` in _styles.xml_.

**Comment by since85stas** [comment]
It's working. You are a magician). I wish to understand what it means, thanks a lot.

**Comment by Risovas** [comment]
@Kvaibhav01 As since85stas said, this really fixed the problem, and I appreciate that a lot. This is not a big problem actually, but even after doing this, the preview doesn't show the app's action bar with the title. That shouldn't be a big problem really, but I get kind of confused with the dimensions of one of the elements that looks a little bigger in the preview than it actually is since there's no action bar in it. Could you try to do some more magic and help me sort this out? :P

**Comment by Kvaibhav01** [comment]
@HuskyTheNoob, if you need to add app's title in the Action Bar, then add the following in your MainActivity.java:

`setTitle("My title");`

If the Action Bar is itself not visible, then make sure you have this:

`<style name="AppTheme" parent="Base.Theme.AppCompat.Light.DarkActionBar"`
Instead of:
`<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar"`
in _styles.xml_.

**Comment by yucoz** [comment]
I have same problem but it looks little different. 
I shared the error messages i received. When i follow your path:

1-- > change the theme from Theme.AppCompat.Light.DarkActionBar to Base.Theme.AppCompat.Light.DarkActionBar in styles.xml.

2-->MainActivity.java:

setTitle("My title");

i don't have any error messages, idon't have even action bar and program is not getting settled in my phone ..





Errors: 
Failed to load AppCompat ActionBar with unknown error.


The following classes could not be instantiated:
- android.support.v7.widget.AppCompatImageView (Open Class, Show Exception, Clear Cache)
- android.support.v7.widget.Toolbar (Open Class, Show Exception, Clear Cache)
- android.support.v7.widget.AppCompatTextView (Open Class, Show Exception, Clear Cache)
- android.support.v7.widget.ActionBarContextView (Open Class, Show Exception, Clear Cache)
- android.support.v7.app.WindowDecorActionBar (Open Class, Show Exception, Clear Cache)
- android.support.v7.widget.ActionBarOverlayLayout (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.  Exception Details java.lang.ClassNotFoundException: android.support.v4.view.TintableBackgroundView Copy stack to clipboard

**Comment by yucoz** [comment]
oohh sorry , i have some messages from Logcat : 

.. E/GooglePlayServicesUtil: The Google Play services resources were not found. Check your project configuration to ensure that the resources are included.
.. E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'TIME_NS' not found
... E/NetlinkEvent: NetlinkEvent::FindParam(): Parameter 'UID' not found

**Comment by yucoz** [comment]
Solved : with updating all versions written lines with  the latest version! :D

**Comment by Kvaibhav01** [comment]
@yucoz now you can close the issue!

**Comment by nano-fruit** [comment]
If you still don't see the action bar.. change the default theme to NoActionBar themes.. try other themes and refresh.. I got it right with Show System UI option in the eye symbol and Changing theme to AppCompact.NoActionBar. This worked for me.
