### ISSUE TITLE
Can't run app on Virtual Device

### ISSUE THREAD

**Issue by since85stas** [udacity/ud839_Miwok#65]
Can't run app on virtual device, preview works fine. Maybe some problems with APK versions? What i'm noticing thats an errorr in Manifest file
![default](https://user-images.githubusercontent.com/35011324/34916754-3c71fe2c-f94e-11e7-9487-c5cef56e7c4d.jpg)
But i dont see some errorrs on building app

**Comment by Kvaibhav01** [comment]
This is normal. Open the emulator before you rebuild the project (Build > Rebuild Project). Then try to run the app on AVD. If the app still doesn't open, add the logcat/messages here.

As for the _concrete class_ error, try to remove/comment any `abstract` method in your MainActivity.java file. Else you may need to implement `OnConnectionSuspended(int)` method. See [here](https://stackoverflow.com/a/31882530).

**Comment by since85stas** [comment]
Error in manifest file has gone when i'm delete Abstract as you say, thx.  And app now running well, so it was a problem. But maybe you can explain smth to me, at first why app building well with this manifest error ? I think that all errors displays while building, or manifest it smth different, difficult for me i'am novice in android.

**Comment by Kvaibhav01** [comment]
This is a basic OOP ([Object Oriented Programming](https://en.wikipedia.org/wiki/Object-oriented_programming)) concept. **When you implement an `interface` you should implement all its methods.** 

An [`abstract` method](https://docs.oracle.com/javase/tutorial/java/IandI/abstract.html) is used when we don't want its objects to instantiate/use anywhere else in the program. In this situation we didn't want to use any related objects of the abstract method therefore we remove that.
