### ISSUE TITLE
Its not compiling correctly

### ISSUE THREAD

**Issue by efanious** [udacity/ud839_Miwok#66]
This is the error that comes up in my messages.

Error:Unknown host 'services.gradle.org'. You may need to adjust the proxy settings in Gradle.

**Comment by Pav2712** [comment]
This might be like the blind leading the blind and I don't know if it will help but I copied and pasted your error into a search and got this ....  Don't know if u already tried that ?

https://stackoverflow.com/questions/33664820/errorunknown-host-services-gradle-org-you-may-need-to-adjust-the-proxy-setting

**Comment by efanious** [comment]
It didn't work but I found another method which helped me resolve the issue... Thanks for the help

**Comment by Kvaibhav01** [comment]
@efanious, you may now close the issue!

**Comment by efanious** [comment]
Okay
