### ISSUE TITLE
NumbersActivity.java problem

### ISSUE THREAD

**Issue by since85stas** [udacity/ud839_Miwok#69]
![problem02](https://user-images.githubusercontent.com/35011324/35765609-acf59034-08d8-11e8-803b-22fa55349dc5.jpg)
This problem appeared when i'm rename Numbers_Activity.xml in Words_list.xml. And i'm cant understand whats wrong(

**Comment by Kvaibhav01** [comment]
Looks like you initialized the `listView` adapter to null or din't initialized at all. Can you provide or check what the logcat says in the _caused by:_ reference. That'll provide you the exact cause of the problem.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
