### ISSUE TITLE
Error:Invalid directory name NOT 

### ISSUE THREAD

**Issue by fairfaxone** [udacity/ud839_Miwok#70]
Information:Gradle tasks [:app:assembleDebug]
C:\Desktop\ud839_Miwok-lesson-one\ud839_Miwok-lesson-one\app\src\main\res\mipmap-hdpi1
Error:Error: Invalid resource directory name
Error:Execution failed for task ':app:mergeDebugResources'.
> C:\Users\OM\Desktop\ud839_Miwok-lesson-one\ud839_Miwok-lesson-one\app\src\main\res\mipmap-hdpi1: Error: Invalid resource directory name
Information:BUILD FAILED in 1s
Information:2 errors
Information:0 warnings
Information:See complete output in console

what could be done 
please help

**Comment by Kvaibhav01** [comment]
1. Make sure you rename all your image files used in the project correctly (usually all in small case).
2. If you have a _values-11_ in the project directory then delete that. It's safe to delete. See [here](http://developer.android.com/guide/topics/resources/providing-resources.html).
3. Rebuild and clean the project.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
