### ISSUE TITLE
cannot find symbol variable number_one ad all numbers

### ISSUE THREAD

**Issue by dzo89** [udacity/ud839_Miwok#71]
Error:(83, 36) error: cannot find symbol variable number_one

 **words.add(new Word(R.string.**# number_one, R.string.miwok_number_one,****
                R.drawable.number_one, R.raw.number_one));
        words.add(new Word(R.string.number_two, R.string.miwok_number_two,
                R.drawable.number_two, R.raw.number_two));
        words.add(new Word(R.string.number_three, R.string.miwok_number_three,
                R.drawable.number_three, R.raw.number_three));

**Comment by Kvaibhav01** [comment]
This means that you haven't used or initialized the `number_one` variable in your current activity. Please make sure to initialize it.
A screenshot of logcat will be better for further issues.

**Comment by dzo89** [comment]
it is done but problem now about style.xml

**Comment by Kvaibhav01** [comment]
Please show us the actual error message.

**Comment by mma87** [comment]
I had the same issue, you can copy the list of the arraylist form the backup you make of the miwok app or add in the string.xml file all the translation. I don't know why but in the code provided there is this error

**Comment by SudKul** [comment]
Should you (or any learner) need help on individual issues, we recommend using the https://knowledge.udacity.com/ platform to discuss with our experienced mentors.
