### ISSUE TITLE
error with variable (words)

### ISSUE THREAD

**Issue by GLOBM** [udacity/ud839_Miwok#73]
public class NumbersActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_numbers);

// Create an array of words
        +        ArrayList<String> words = new ArrayList<String>();
        +        words.add("one");
        +        words.add("two");
        +        words.add("three");
        +        words.add("four");
        +        words.add("five");
        +        words.add("six");
        +        words.add("seven");
        +        words.add("eight");
        +        words.add("nine");
        +        words.add("ten");

        LinearLayout rootView = (LinearLayout)findViewById(R.id.rootView);
        TextView wordView = new TextView(this);
        wordView.setText(words.get(0));
        rootView.addView(wordView);
    }
}

**Comment by GLOBM** [comment]
ok , got it

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
