### ISSUE TITLE
Unable to View Log messages from Logcat

### ISSUE THREAD

**Issue by babsdalley** [udacity/ud839_Miwok#74]
I have printed my array elements to the logs, but I can't seem to view them. Here is the code

![image](https://user-images.githubusercontent.com/18751612/36207646-dec4fcfa-1196-11e8-858a-8cc60242c724.png) 

Here is a screenshot of my logs after running the app:
![image](https://user-images.githubusercontent.com/18751612/36207755-43e33f20-1197-11e8-8b02-939e14b4f9be.png)

The Udacity instructor said she navigated to the NumbersActivity under the logcat. Is there anything I'm missing?

**Comment by mbeltrandelrio** [comment]
I am in the same boat as you.  Did not see any printed log cat messages for the array or for the arraylist.
06-07 18:01:05.600 16130-16130/? E/Zygote: v2
06-07 18:01:05.600 16130-16130/? I/libpersona: KNOX_SDCARD checking this for 10276
    KNOX_SDCARD not a persona
06-07 18:01:05.601 16130-16130/? E/Zygote: accessInfo : 0
06-07 18:01:05.601 16130-16130/? W/SELinux: SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SECMOBILE_7.0_0009, [-1 -1 -4 -1 0 1]
06-07 18:01:05.602 16130-16130/? I/SELinux: SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.example.android.miwok 
06-07 18:01:05.605 16130-16130/? I/art: Late-enabling -Xcheck:jni
06-07 18:01:05.628 16130-16130/? D/TimaKeyStoreProvider: TimaKeyStore is not enabled: cannot add TimaSignature Service and generateKeyPair Service
06-07 18:01:05.914 16130-16130/com.example.android.miwok W/System: ClassLoader referenced unknown path: /data/app/com.example.android.miwok-2/lib/arm64
06-07 18:01:05.933 16130-16130/com.example.android.miwok I/InstantRun: starting instant run server: is main process
06-07 18:01:06.015 16130-16130/com.example.android.miwok W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
06-07 18:01:06.073 16130-16130/com.example.android.miwok D/ViewRootImpl@9c7712b[MainActivity]: ThreadedRenderer.create() translucent=false
06-07 18:01:06.077 16130-16130/com.example.android.miwok D/InputTransport: Input channel constructed: fd=71
06-07 18:01:06.077 16130-16130/com.example.android.miwok D/ViewRootImpl@9c7712b[MainActivity]: setView = DecorView@a87988[MainActivity] touchMode=true
06-07 18:01:06.091 16130-16130/com.example.android.miwok D/ViewRootImpl@9c7712b[MainActivity]: dispatchAttachedToWindow
06-07 18:01:06.114 16130-16130/com.example.android.miwok D/ViewRootImpl@9c7712b[MainActivity]: Relayout returned: oldFrame=[0,0][0,0] newFrame=[0,0][1440,2560] result=0x27 surface={isValid=true 522746963456} surfaceGenerationChanged=true
    mHardwareRenderer.initialize() mSurface={isValid=true 522746963456} hwInitialized=true
06-07 18:01:06.129 16130-16194/com.example.android.miwok D/libEGL: loaded /vendor/lib64/egl/libGLES_mali.so
06-07 18:01:06.155 16130-16194/com.example.android.miwok I/OpenGLRenderer: Initialized EGL, version 1.4
06-07 18:01:06.155 16130-16194/com.example.android.miwok D/OpenGLRenderer: Swap behavior 1
06-07 18:01:06.160 16130-16194/com.example.android.miwok D/mali_winsys: EGLint new_window_surface(egl_winsys_display*, void*, EGLSurface, EGLConfig, egl_winsys_surface**, egl_color_buffer_format*, EGLBoolean) returns 0x3000,  [1440x2560]-format:1
06-07 18:01:06.204 16130-16130/com.example.android.miwok W/art: Before Android 4.1, method int android.support.v7.widget.ListViewCompat.lookForSelectablePosition(int, boolean) would have incorrectly overridden the package-private method in android.widget.ListView
06-07 18:01:06.210 16130-16130/com.example.android.miwok D/ViewRootImpl@9c7712b[MainActivity]: MSG_RESIZED_REPORT: ci=Rect(0, 96 - 0, 0) vi=Rect(0, 96 - 0, 0) or=1

**Comment by Kvaibhav01** [comment]
I think you need to clean up the previous log messages in the logcat by clicking on the bin icon to the left of logcat window and then run the app again. 

If you're still not able to find it, try to search for the specific log in the search box of the logcat window.

**Comment by babsdalley** [comment]
I decidedto go on with the course, and then later on it started showing. Don't pay too much attention to it. You're good to go!

**Comment by Kvaibhav01** [comment]
Kindly close the issue @babsdalley

**Comment by sandidutt2** [comment]
I am having the same problem.Log message is not coming in Logcat inspite of writing the same code which mam has provided

**Comment by Kvaibhav01** [comment]
@sandidutt2 did you tried the [above solution](https://github.com/udacity/ud839_Miwok/issues/74#issuecomment-395782737)?

Also, you can do this:

1. Go to Run -> Edit Configurations
2. Select the Miscellaneous tab and select _Show logcat automatically_ and _Clear log before launch_.
3. Restart

**Comment by yash17525** [comment]
For easily finding your log messages you have to search with the word "NumbersActivity" in the search tab provided in logcat.
![screenshot from 2018-10-10 21-48-36](https://user-images.githubusercontent.com/33418013/46750933-cc73aa00-ccd6-11e8-8332-e5cdec7a1083.png)

**Comment by yash17525** [comment]
There may be one another reason for the log messages not to appear.When you run your project for the ,the logcat will not show the NumbersActivity messages until you click the Numbers button on your device or emulator.
Given below is state of emulator before pressing Numbers button...
![screenshot from 2018-10-10 22-09-10](https://user-images.githubusercontent.com/33418013/46751966-ab608880-ccd9-11e8-9533-59f9963781bd.png)
Given below is state of emulator after pressing Numbers button.
![screenshot from 2018-10-10 22-11-04](https://user-images.githubusercontent.com/33418013/46752025-cd5a0b00-ccd9-11e8-9a4f-6ef185cf1f31.png)

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
