### ISSUE TITLE
ssl peer shutdown incorrectly 

### ISSUE THREAD

**Issue by Hisham691** [udacity/ud839_Miwok#75]
I'm having this error when trying to open the project.
any ideas?

![untitled](https://user-images.githubusercontent.com/36056543/36238070-316ef3d2-1211-11e8-9982-93f1fb772a2e.png)

**Comment by Kvaibhav01** [comment]
Try to rebuild the project. Also look out for Android SDK Manager. Go to "Options" in the "Tools" menu, and check the option **"Force https://... sources to be fetched using http://...".**

**Comment by Hisham691** [comment]
Thanks for replying .. i tried both things you said but non of them worked.

**Comment by Kvaibhav01** [comment]
Maybe you need to go to the _gradle-wrapper.properties_ file under Gradle scripts and change the `distributionUrl` value to the Gradle version your project uses to compile. See [this answer](https://stackoverflow.com/a/41256774).

**Comment by Hisham691** [comment]
i solved this error by downloading the gradle manulay => put the downloaded file in .gradle file and sync .. thanks for your time ❤

**Comment by Kvaibhav01** [comment]
You may now close this issue! 😃
