### ISSUE TITLE
rootView error in NumbersActivity.java

### ISSUE THREAD

**Issue by dewri21** [udacity/ud839_Miwok#76]
LinearLayout rootView = (LinearLayout) findViewById(R.id.rootView);

The rootView with the R.id.rootView gives me an error saying "cannot resolve symbol". I thought I did some mistake with my code somewhere, tried figuring it out and failed. So I just copy pasted the codes for activity_numbers.xml and NumbersActivity.java from here but the problem still persists. Can someone help me out here?

PS: I am using a different package name and that cannot be the issue.

![untitled](https://user-images.githubusercontent.com/9104080/36328719-4e6d53ec-1389-11e8-907b-0ec80867dc97.jpg)

**Comment by Kvaibhav01** [comment]
This means that you haven't assigned the `id` of the `LinearLayout` in your XML file to `rootView`. Check for the spelling errors.
If you really have the same id then you can rebuild and clean the project or save your work and restart Android Studio.

**Comment by dewri21** [comment]
@Kvaibhav01 No, that wasn't the issue. Like I said, I already copied codes for the xml and java files for numbers, just to be sure I wasn't making a typo. A gradle sync fixed it though.
