### ISSUE TITLE
migrate to gradle build

### ISSUE THREAD

**Issue by Akanksha2050** [udacity/ud839_Miwok#77]
after downloading and extracting the zip codes I am getting a message like this.
This project does not use the Gradle build system. We recommend that you migrate to using the Gradle build.
What should I do.Any help would be appreciated.
Thank you.

**Comment by Kvaibhav01** [comment]
Please upgrade to the Gradle build system. That'll remove the error/warning.

**Comment by Akanksha2050** [comment]
how to upgrade to gradle build system?

**Comment by Kvaibhav01** [comment]
Select 'File/Import Project', select your project root directory, and in the next dialog choose 'Import project from external model' and select _gradle_.

**Comment by HishamYoussef** [comment]
which grad;e ? can you explain in details

**Comment by Kvaibhav01** [comment]
@HishamYoussef see this: https://stackoverflow.com/questions/20362473/being-told-project-is-not-using-the-gradle-build-system-when-it-is

**Comment by Fahd4world** [comment]
@Kvaibhav01 there is nothing appear after I import the project. It directly open the file without giving other options ?

**Comment by Kvaibhav01** [comment]
@Fahd4world you need to make sure that Android Studio is using the Gradle build system. This is used to open your Android projects. Also, **please make sure you have .gradle (app and project level) files in the project folder.**

**Comment by Fahd4world** [comment]
@Kvaibhav01  many thanks for replying, I am just new here. 
the app root doesn't include a .gradle file as the rest of the apps I created ! What should I do ? I unzipped the file and imported it directly .
also Could you please tell me how to check if "Android Studio is using the Gradle build system" ?

**Comment by Fahd4world** [comment]
@Kvaibhav01  OH! I found a bat file called gradlew.bat on the root I double click it and it downloaded a lot of files and created the .gradle  file and now I am processing wish everything is ok. ! I wonder why they didnt mention that step !
Thanks Sir

**Comment by Kvaibhav01** [comment]
> I wonder why they didnt mention that step !

Yeah, I agree. For beginners, it should be mentioned somewhere. Anyway, I'm glad that it helped you 😃

**Comment by dcminming** [comment]
I still have a problem with this. When I first import project, there're 2 options: (1) create project from existing sources, or (2) import project from external model. If I choose the 1st option, then I get the error "This project does not use the Gradle build system. We recommend that you migrate to using the Gradle build." 

If I choose the 2nd option, it says "Gradle location is unknown". I can't find the gradlew.bat file that @Fahd4world   mentioned anywhere. 

I'm totally new to this so any help would be appreciated.

**Comment by Kvaibhav01** [comment]
@dcminming , check again, there is a gradlew.bat file in the root directory.
![batfile](https://user-images.githubusercontent.com/11731837/42131819-c2623a98-7d28-11e8-8ac2-3e0f505fdbe1.PNG)

Make sure you've extracted the ZIP filel correctly. And then follow what @Fahd4world did.

**Comment by dcminming** [comment]
Thanks for that. I found the gradlew.bat file and tried what @Fahd4world suggested, but it still doesn't work.  After I select Import project from external model, it still shows Gradle location unknown. Any file that I select from the Miwok starter code doesn't work. Please help! 

![screenshot 4](https://user-images.githubusercontent.com/40705845/42138192-3d8ef738-7d47-11e8-8920-a577ca84f758.png)

**Comment by Kvaibhav01** [comment]
@dcminming , depending on the version of Android Studio, that Gradle directory may be _where/you/installed/android-studio/gradle/gradle-x.y.z_ (x.y.z is the version, so check your filesystem for the exact path)

**Comment by sneha123** [comment]
if using android 3.1.3 use this in build.gradle
implementation 'com.android.support:design:23.4.0'
It worked for me

**Comment by SudKul** [comment]
We have updated all branches to use Gradle 7.x, SDK API level 31, and AndroidX dependencies.
