### ISSUE TITLE
Lesson-Five Branch won't compile

### ISSUE THREAD

**Issue by mrk-han** [udacity/ud839_Miwok#79]
Lesson-five branch of the Miwok Repo, won't compile.

```
R.string.miwok_number_one
```
does not exist, but is used in `words.add(new Word());` for the `final ArrayList<Word> words = new ArrayList<Word>();`

**Comment by mrk-han** [comment]
This error was found in Step 11 of Section 6 (Optional) Fragments.

`As a sanity check, this is the end result of the NumbersFragment class.`

**Comment by SudKul** [comment]
We have updated and tested all branches to use Gradle 7.x, SDK API level 31, and AndroidX dependencies.
