### ISSUE TITLE
Setting.jar file not found

### ISSUE THREAD

**Issue by amitkumar1983** [udacity/ud839_Miwok#8]
Hi Team
when downloaded project zip file, and trying to import, then getting message "can not find file" " setting.jar" file is not found.

any input ?

**Comment by diwesh87** [comment]
@amitkumar1983 : Once you have downloaded the zip and extracted it, simply Open Android Studio and click on "Import an existing project". Is that how you did ?

**Comment by SarbajeetMaity** [comment]
I am also facing the same problem

**Comment by diwesh87** [comment]
You guys can try deleting the existing build file and then Build ----> Clean Project

**Comment by Dav-i-d** [comment]
This is prior to opening project upon import.

**Comment by Kvaibhav01** [comment]
Try removing the _Build_ file then perform _Clean Project_, then _rebuild_ your project.

**Comment by MHassan16** [comment]
hey guys i am facing the same problem it say cannot find settings. jar and i cant understand what is the mean by removing the build file and perform clean project

**Comment by Kvaibhav01** [comment]
Hi @MHassan16, the only solution is to remove the build file, clean and rebuilding the project. Source: https://stackoverflow.com/a/34397510

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code
