### ISSUE TITLE
Failed to load AppCompat ActionBar with unknown error in android studio

### ISSUE THREAD

**Issue by abdullah-alialdin** [udacity/ud839_Miwok#80]
After importing the project Miwok from GitHub and make all needed updates I found that there is no review with an error message "Failed to load AppCompat ActionBar with unknown error in android studio"
![capture](https://user-images.githubusercontent.com/36700590/37238583-520122ea-2432-11e8-8422-371295f35ec2.JPG)
After a google search, I find the solution
in style.xml
Change <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
to <style name="AppTheme" parent="Base.Theme.AppCompat.Light.DarkActionBar">
![capture2](https://user-images.githubusercontent.com/36700590/37238610-ce306b0a-2432-11e8-9eb4-ed37b579c1d2.JPG)

**Comment by Kvaibhav01** [comment]
So, the solution worked? Are you still facing the same issue?

**Comment by abdullah-alialdin** [comment]
@Kvaibhav01, Yes the solution worked well and there is no issue till now :D

**Comment by Nikoloutsos** [comment]
Thank you for sharing this solution with us! I was facing this problem ;/

**Comment by Kvaibhav01** [comment]
@Eng-navyman you may close this issue now.

**Comment by beethovenelie** [comment]
Thank you for sharing
