### ISSUE TITLE
error:Error:Could not GET 'https://jcenter.bintray.com/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar'. Received status code 502 from server: Bad Gateway <a href="toggle.offline.mode">Enable Gradle 'offline mode' and sync project</a>

### ISSUE THREAD

**Issue by anongorax** [udacity/ud839_Miwok#82]
I recently imported this project from your github repository and when this project was syncing it showed error : Error:Could not GET 'https://jcenter.bintray.com/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar'. Received status code 502 from server: Bad Gateway
<a href="toggle.offline.mode">Enable Gradle 'offline mode' and sync project</a>
and i clicked this link Enable Gradle 'offline mode' and sync project and synced and failed again saying Error:Could not download asm.jar (org.ow2.asm:asm:5.0.3): No cached version available for offline mode 
please help me !!
if this promblem wont get solved i will be stucked on practising the udacity course!!!

**Comment by Kvaibhav01** [comment]
1. Make sure you have an active and steady internet connection.
2. Try to Clean/Rebuild the project.
3. Try Invalidate caches/Restart.
4. Make sure you have `maven {   url "https://maven.google.com"  }` in your project-level build.gradle file.

**Comment by javabiker** [comment]
This proposed solution did not work for me - got same message.  Happened during update to AS to 3.1.1
from AS 3.0.1.

**Comment by Kvaibhav01** [comment]
@javabiker AS 3.1.1 still contains some bugs. Try to downgrade and run it again with the solutions given above.

**Comment by befairyliu** [comment]
android studio 3.2 has the same bug

**Comment by Kvaibhav01** [comment]
@befairyliu, have you tried [enabling Gradle offline mode](https://stackoverflow.com/a/30794890) and then syncing the project? Make sure to ENABLE it.

**Comment by iamsabbir12** [comment]
same here

**Comment by YuriyBereguliak** [comment]
I was faced with the same issue when my internet connection is really bad. When the connection has been restored, everything must work.

**Comment by SudKul** [comment]
Solution proposed by @Kvaibhav01 seems good for a fresh start.
