### ISSUE TITLE
Error Configuration 'compile' is obsolete and has been replaced with 'implementation'. It will be removed at the end of 2018   Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation'. It will be removed at the end of 2018   Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'. It will be removed at the end of 2018

### ISSUE THREAD

**Issue by mega911911911** [udacity/ud839_Miwok#83]

**Comment by Kvaibhav01** [comment]
Kindly specify the issue heading in short above and describe it in the box.

**Comment by Konstantin-Pavlov** [comment]
I have this too

**Comment by syahrulhajji** [comment]
The solution is to upgrade classpath com.google.gms:google-services to classpath 'com.google.gms:google-services:3.2.0' in file in build.gradle

**Comment by Arthurfb** [comment]
I did what syahrulhajji said, and i got this problem "Plugin with id 'com.android.application' not found."

**Comment by mseiimeorn** [comment]
In the build.gradle app, try to change 'compile' to 'implementation' and 'testCompile' to 'testImplementation' . Additionally check your versions there (e.g. change 23.3.0 to 23.4.0, but there will be a tooltip) ... at least for me it seemed to work so far

**Comment by Arthurfb** [comment]
Its working now, thanks man

**Comment by harryschmach** [comment]
Thank you @mseiimeorn !

**Comment by Sanjeevi567** [comment]
Thanks lotttt...........

**Comment by Kvaibhav01** [comment]
@mega911911911 kindly see this and close the issue if your problem is solved.

**Comment by sambit-m** [comment]
Solved it!
Follow these simple steps :
1.Open a new project. Go to Gradle Script->build.gradle(Module:app)
2.Copy the whole thing in that file and replace it in your build.gradle(Module:app) in Miwok project.
3.Change the applicationId to "com.example.android.miwok"

Note: After compilation if your preview doesn't show anything then goto styles.xml(app->res->values or keyboard shortcut ctrl+shift+n then type styles.xml) and change parent to "Base.Theme.AppCompat.Light.DarkActionBar"

PS: @mseiimeorn did the same thing :-)

**Comment by SumitJaglan** [comment]
Its working..... Thanks @syahrulhajji

**Comment by raymond3572** [comment]
I only replaced the words they said were no longer being used. The errors went away.
My code below.

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    testImplementation 'junit:junit:4.12'
    implementation 'com.android.support:appcompat-v7:23.3.0'
    androidTestImplementation 'com.android.support:support-v4:23.3.0'
    androidTestImplementation 'com.android.support:design:23.3.0'

**Comment by TafaraMakaza** [comment]
Just go to your gradle App level file and replace "compile" with
"implemantation"

Tafara Makaza
Cofounder at Famkeepa Inc
Williams College, BA Physics'20
Clinton Global Initiative University Campus Rep 2018
Cell .  : 413-884-5191
email .: tm6@williams.edu

**Comment by allabux** [comment]
Thank you mseiimeorn

**Comment by SagarGiri2104** [comment]
[![enter image description here][1]][1]

**Explaination:**

since the **compile** is been obsolete in 2018 you must change this configuration as follows:
 1. open **build.gradle(module:app)** app file and make following changes in it.
 2. replace **compile** with **api** wherever api ref. like: volley, GitHub dependancy.strong text is used and
 3. replace **compile** with **implementation** incase of using android libraries like play-services-maps,appcompat-v7 etc.

example:
old way
 

      dependencies {
         testCompile'junit:junit:4.12'
        compile 'com.android.volley:volley:1.1.0' 

Change it to:

     dependencies {
        testImplementation 'junit:junit:4.12'
        implementation 'com.android.volley:volley:1.1.0'

if the issue still persists:

open **build.gradle (Project: yourproject)** file
and change the google gms services to the latest 

    dependencies {
            classpath 'com.android.tools.build:gradle:3.2.1'
            
    
            // NOTE: Do not place your application dependencies here; they belong
            // in the individual module build.gradle files
        }

Also if the gradle sync is still failing:

Open **gradle-wrapper.properties** file and replace it with following:

    distributionBase=GRADLE_USER_HOME
    distributionPath=wrapper/dists
    distributionUrl=https\://services.gradle.org/distributions/gradle-4.6-all.zip
    zipStoreBase=GRADLE_USER_HOME
    zipStorePath=wrapper/dists


  [1]: https://i.stack.imgur.com/TKDWn.png

**Comment by euclidesduarte5** [comment]
@mseiimeorn thank you

**Comment by Nidal-Bakir** [comment]
@mseiimeorn  thenk you

**Comment by anurag524sagar** [comment]
> Its working now, thanks man

**Comment by aarifali** [comment]
i already changed everything  compile to  implementation but give me same error

 implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.nostra13.universalimageloader:universal-image-loader:1.9.5'
    implementation 'com.github.javiersantos:MaterialStyledDialogs:2.1'
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support:support-v4:28.0.0'
    implementation 'com.google.android.gms:play-services-maps:11.8.0'
    implementation 'com.google.firebase:firebase-database:11.8.0'
    implementation 'com.google.firebase:firebase-core:11.8.0'
    // this line must be included to integrate with Firebase
    implementation 'com.google.firebase:firebase-messaging:11.8.0'
    implementation 'com.android.support:cardview-v7:28.0.0'
    implementation 'com.android.support:recyclerview-v7:28.0.0'
    implementation 'com.google.code.gson:gson:2.6.2'
    implementation 'com.squareup.retrofit2:retrofit:2.0.2'
    implementation 'com.squareup.retrofit2:converter-gson:2.0.2'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    implementation 'de.hdodenhof:circleimageview:1.2.1'
    implementation 'com.squareup.picasso:picasso:2.71828'

    implementation 'it.neokree:MaterialTabs:0.11'

**Comment by SudKul** [comment]
We have updated all branches to use Gradle 7.x, SDK API level 31, and AndroidX dependencies.
