### ISSUE TITLE
All screens in the AndroidManifest show that they are not assignable to 'android.app.Activity'

### ISSUE THREAD

**Issue by ghost** [udacity/ud839_Miwok#85]
Hi guys. Please could you check this error message and provide any solution?
I'm importing and old code to Andoid Studio 3.1.2. All projects created with this new version of Android Studio are working perfectly, but just this one old code project is not working.

**AndroidManifest.xml**
![miwok](https://user-images.githubusercontent.com/13338743/39685336-954d8f34-5187-11e8-9766-5de49595e834.png)

**build.gradle**
![build_gradle](https://user-images.githubusercontent.com/13338743/39685360-c49630a2-5187-11e8-8acd-0fda82906fa5.png)

**Comment by Kvaibhav01** [comment]
First, make sure you update the build tools version as suggested by AS. Then clean the project.
Next, make sure your activity is extending a `FragmentActivity` and not a `Fragment` if you've used a `Fragment`. Rebuild the project again.

**Comment by moharidy** [comment]
where to change the fragment reference?

**Comment by Kvaibhav01** [comment]
Just change `extends Fragment` to `extends FragmentActivity` in your Java file and rebuild/clean project.

**Comment by nsteve-one** [comment]
I am having the same problem. I have my main activity, and my other activities, extending `AppCompatActivity`. I am getting the same "not assignable" error. The error goes away if my MainActivity extends `Activity`.

Everything builds and runs correctly, I have just started this project.

**Comment by nsteve-one** [comment]
I did something (I'm not exactly sure what I did, I've been trying the same things for an hour), and now it works.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo.
