### ISSUE TITLE
Cannot Resolve AppCompatActivity

### ISSUE THREAD

**Issue by CM747** [udacity/ud839_Miwok#86]
Its saying "Cannot resolve AppCompatActivity"

![screenshot 3](https://user-images.githubusercontent.com/32798401/40298511-05a672d0-5d01-11e8-81eb-de34a205726e.png)
![screenshot 4](https://user-images.githubusercontent.com/32798401/40298515-0a410a6c-5d01-11e8-85b3-faad8f8a9def.png)

**Comment by lorenzhunter** [comment]
Hi CM747, I have the same issue. How did you solve it?

**Comment by engmoha** [comment]
You can solve this problem by changing the number 3 to 4 on each line where the number 3 is written from the beginning : implementation 'com.android.support:appcompat-v7:23.4.0'  instead of  implementation 'com.android.support:appcompat-v7:23.3.0' then do that in each line later
