### ISSUE TITLE
some warnings and import appcompatactivity is not working

### ISSUE THREAD

**Issue by joey-jiang6** [udacity/ud839_Miwok#89]
still having this issue, had tried all the solutions above. it didnt work.
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
WARNING: Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'.
WARNING: Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.

having this three warning, the app can be compile but ..
import android.support.v7.app.AppCompatActivity;
cant be import , I dont know why

**Comment by Kvaibhav01** [comment]
For warnings like _Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'_, you can just replace the word `compile` to `implementation`.

For 
> import android.support.v7.app.AppCompatActivity;
> cant be import , I dont know why

Just do the  File->Invalidate Caches/Restart.

**Comment by joey-jiang6** [comment]
thanks for your explanation:)

**Comment by Kvaibhav01** [comment]
If your problem is solved then kindly close this issue 😄
