### ISSUE TITLE
Error:Could not download gradle-core.jar (com.android.tools.build:gradle-core:2.1.0): No cached version available for offline mode

### ISSUE THREAD

**Issue by Tripatpal** [udacity/ud839_Miwok#9]
I encountered this error while importing project, any inputs?

Error:Could not download gradle-core.jar (com.android.tools.build:gradle-core:2.1.0): No cached version available for offline mode

**Comment by elyashadizadeh** [comment]
as the error description says, " No cached version available for offline mode", so you need to turn on gradle and rebuild application, in order to do this: File-->Settings -->Build, Executions, Deployment -->  Build Tools --> Gradle --> uncheck the "offline work" --> click on the apply button --> rebuild your application

have fun

**Comment by Tripatpal** [comment]
@elyashadizadeh Oh thank you very much! (After I Unchecked the "Offline work", Rebuilding application didn't help, but i imported the project again and this time instead of giving error some update of SDK operation ran and opened the project). Thank you once again.

**Comment by seyidaniels** [comment]
If working on react-native, and you are trying to run the android build, try changing the class path in your build.gradle path from         classpath 'com.android.tools.build:gradle:3.1.4'
to         classpath 'com.android.tools.build:gradle:3.0.1'

**Comment by Mehulipal** [comment]
@elyashadizadeh Thanks a lot :)

**Comment by ashajep** [comment]
i change the classpath from 'com.android.tools.build:gradle:3.0.1 to 'com.android.tools.build:gradle:3.5.3' in the build.gradle

**Comment by abhi790** [comment]
As in my case, it is not the problem with the Miwok app, it simply the project is not in sync with the Gradle. 
To make it syn you have to do the following-->
1.Go to Gradle(View-->Tool Window-->Gradle)
2.Toggle the Offline mode.
![gradle](https://user-images.githubusercontent.com/64580344/97139961-b3d17200-1781-11eb-8172-c5fd8a0d427d.png)
3.Go to File 
4.Click Sync Project with Gradle File.
Make sure you are connected to the internet to download the required file, be patience if you have a slow internet connection, bz it would take some time to complete.
You are done, enjoy.
