### ISSUE TITLE
Miwok

### ISSUE THREAD

**Issue by kakarotoSUPER** [udacity/ud839_Miwok#92]
I have issue when i tried to add new Activity (numberActivity) an error  appear about compile and when i tried to add another activity i could't because the is saw (activity(project not ready ))  and the manifests  file disappear I need help.

**Comment by Kvaibhav01** [comment]
I think _Project not ready_ means that the Gradle build is not complete in your project. Try to clean and sync your project.

**Comment by SudKul** [comment]
Should you (or any learner) need help on individual issues, we recommend using the https://knowledge.udacity.com/ platform to discuss with our experienced mentors.
