### ISSUE TITLE
Cannot resolve constructor 'Intent(

### ISSUE THREAD

**Issue by mbeltrandelrio** [udacity/ud839_Miwok#93]
The MainActivity.java file is underlined with a red squiggly line.  and so is the input of the intent.  The error reads 

Cannot resolve constructor 'Intent(com.example.android.miwok.MainActivity, java.lang.Class<com.example.android.miwok.NumbersActivity>)'

ALSO startActivity is red  Cannot resolve method 'startActivity(android.content.Intent)'

public void onClick(View view) {
                Intent numbersIntent = new Intent(MainActivity.this, NumbersActivity.class);
                startActivity(numbersIntent);
            }

I tried StackOverflow...........they recommended adding .getActivity() after .this but that did not work just got another Cannot resolve method getActivity.....

Other than this.....the LOG CAT IS NOT DISPLAYING ANY OF THE ARRAY OR ARRAYLIST ELEMENTS and I'm not sure if its connected to having these other unresolved issues.  I've spent hours troubleshooting various items on this project.  I was successful at the AppCompatActivity....but this has been a long never ending debugging imported piece of code.

Help?

**Comment by mbeltrandelrio** [comment]
My mentor resolved the following:
Cannot resolve constructor 'Intent(com.example.android.miwok.MainActivity, java.lang.Class<com.example.android.miwok.NumbersActivity>)'

with writing:    Intent numbersIntent = new Intent(view.getContext(), NumbersActivity.class);

Also, Cannot resolve method 'startActivity(android.content.Intent)'

with writing: view.getContext().startAvtivity(numbersIntent);

**Comment by Kvaibhav01** [comment]
I hope that solved your problem? If yes, then kindly close this issue.

**Comment by alzizou** [comment]
this solution solved my issue.

**Comment by Failrule** [comment]
@mbeltrandelrio Thank you!

**Comment by hym999** [comment]
I have the same problem.Your method also solved my problem.Thank you very much

**Comment by renadayne** [comment]
> My mentor resolved the following: Cannot resolve constructor 'Intent(com.example.android.miwok.MainActivity, java.lang.Class<com.example.android.miwok.NumbersActivity>)'
> 
> with writing: Intent numbersIntent = new Intent(view.getContext(), NumbersActivity.class);
> 
> Also, Cannot resolve method 'startActivity(android.content.Intent)'
> 
> with writing: view.getContext().startAvtivity(numbersIntent);

tks u very much =))
