### ISSUE TITLE
please help 

### ISSUE THREAD

**Issue by ahmed-elbassosy** [udacity/ud839_Miwok#95]
Hello,, 

Any help please it's very important and I couldn't find any solution .
Thanks and regards

![help](https://user-images.githubusercontent.com/39389844/41974333-f7f980da-7a17-11e8-80bd-32a478571d5d.JPG)
![help1](https://user-images.githubusercontent.com/39389844/41974336-f82c288c-7a17-11e8-8e64-ec93ddbbae4b.JPG)
![capture](https://user-images.githubusercontent.com/39389844/41974337-f85db136-7a17-11e8-9db2-bfdce7d17547.JPG)

**Comment by Kvaibhav01** [comment]
Just use `compile` instead of `implementation` in your _build.gradle_ file (app-level).
