### ISSUE TITLE
I cant import the project correctly 

### ISSUE THREAD

**Issue by FU00FU** [udacity/ud839_Miwok#96]
![error](https://user-images.githubusercontent.com/40773759/42182183-72e719f8-7e4e-11e8-883b-fa82b168d332.png)

I followed the instructors and this is the result

**Comment by Kvaibhav01** [comment]
Try to clean/rebuild project or clone the repo via Git Bash/Terminal.

**Comment by sambit-m** [comment]
Follow this issue https://github.com/udacity/ud839_Miwok/issues/83
You'll find the solution from mseiimeorn or me

**Comment by Kvaibhav01** [comment]
Yes, as @sambit-m said check out this: https://github.com/udacity/ud839_Miwok/issues/83#issuecomment-386696406

**Comment by dhairyap99** [comment]
No toolchains found in the NDK toolchains folder for ABI with prefix: mipsel-linux-android

I am getting this error please help

**Comment by Kvaibhav01** [comment]
Hey @dhairyap99, just add the following in the project level Gradle:

`classpath "com.android.tools.build:gradle:3.2.0"`

i.e you just need to make sure that you upgrade the Android Gradle plugin to **3.1 or newer**.

**Comment by SudKul** [comment]
Now, we recommend these steps:

How to use this repository?
--------------
- Fork this repository to your Github account.
- Open Android Studio 3.2.x+ in your local machine.
- We recommend you to use the [Version Control System](https://developer.android.com/studio/intro#version_control_basics)(VCS) in your Android Studio 3.2.x+ IDE to clone the repository directly in your IDE.
- You may have to use the File > Settings > Version Control (VCS) menu option to set up Git settings.
- Refer to this [IntelliJ document](https://www.jetbrains.com/help/idea/version-control-integration.html) for details.
- Working with VCS will make it easy for you to push your updates or switch between branches to your remote repository in Github.

**Comment by SudKul** [comment]
Should you (or any learner) need help on individual issues, we recommend using the https://knowledge.udacity.com/ platform to discuss with our experienced mentors.
