### ISSUE TITLE
cannot resolve 'Theme'

### ISSUE THREAD

**Issue by chillandpaybills** [udacity/ud839_Miwok#97]
In the styles.xml file it gives an err0r saying cannot resolve 'Theme' in 
 <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
and maybe that's the reason the click on the numbers textview doesn't respond.
Please Help
Thankyou

**Comment by Kvaibhav01** [comment]
You can try these:

- Clean and rebuild your project
- Do Invalidate Caches/Restart
- Check if your project has `implementation 'com.android.support:appcompat` library added with correct version
- In your project level Gradle file look for `com.android.tools.build:gradle` line.  Its version should match the version of Android Studio which you're using. Like if you're on version 3.1.2 then it should be `com.android.tools.build:gradle:3.1.2`. Rebuild the project after you make the correction.

**Comment by johnshea** [comment]
Closing this issue as it is not related to the repo's code.
