### ISSUE TITLE
Miwok App

### ISSUE THREAD

**Issue by RahmaRabee** [udacity/ud839_Miwok#98]
Cannot download the zip for the app can u please tell me why

**Comment by Kvaibhav01** [comment]
What's the problem you're facing exactly? TO download this repo via a browser you simply need to click on the green button which says 'Clone or download', then click 'Download ZIP'. 

Alternatively, click [here](https://github.com/udacity/ud839_Miwok/archive/lesson-one.zip) to start the download process.

**Comment by RahmaRabee** [comment]
i click the "download zip" and then the pages is loading and nothing happens after
think the prob is in my laptop because it worked when i switched to another device
thank u

**Comment by Kvaibhav01** [comment]
Kindly close the issue if the problem is solved 😀

**Comment by RahmaRabee** [comment]
will do and sorry for the trouble
could u please see if u can help me out on this firs
<img width="960" alt="jkhkjfgkjdxkbjk dhgagjokn" src="https://user-images.githubusercontent.com/40916529/42420817-6d393e0c-82d4-11e8-90c0-9d3018ba1207.PNG">
t

**Comment by Kvaibhav01** [comment]
You need to extract the ZIP first and then open the extracted folder to AS. 

Also, make sure these:
- You have a stable internet connection.
- You click on the Re-download dependencies link and let AS do the task for you. 
- Try to clean/rebuild the project. Sometimes _File -> Invalidate Caches/Restart_ also works.

If the problem still persists, then:

1.  Download the latest Gradle package from [here](http://services.gradle.org/distributions).
2.  Extract it.
3.  Load this project.
4.  Go to _File ->Settings ->Gradle_. Click on _Use local Gradle distribution_. Then use the folder which you extracted in step 2.

**Comment by RahmaRabee** [comment]
Thank u very much
